import type { PartDef } from '../../types'

import { cylX } from './geometry'

function piston(i: number): PartDef {
  return {
    id: `piston-${i + 1}`,
    name: `Piston & Connecting Rod #${i + 1}`,
    system: 'rotating',
    build: 'piston',
    position: [cylX[i], 0.18, 0],
    explodeOffset: [0, 1.5, 0],
    function:
      'Converts combustion pressure into linear force, transmitted through the connecting rod to the crankshaft. The S58 uses forged pistons rated for high boost pressure.',
    location: `Cylinder ${i + 1}, counted from the front (timing end) of the engine.`,
    inspectionNotes:
      'Inspect ring lands, skirt coating, and the rod bearing shells. Check bore cross-hatch before reinstalling. Rod bolts are torque-to-yield: always replace.',
    failurePoints: 'Ring land damage from detonation; rod bearing wear under sustained high load.',
    relatedPartIds: ['crankshaft', 'cylinder-block', 'cylinder-head', 'oil-spray-nozzles'],
    dependencies: ['cylinder-head', 'oil-pan', 'oil-pump'],
    removalOrder: 27 + i,
    difficulty: 3,
    simplified: 'Piston, rings, wrist pin and rod are modeled as one assembly.',
    sources: [
      {
        label: 'BMW S58 forged pistons & closed-deck block — BMW Group technical press',
        labelZh: 'BMW S58 锻造活塞与闭式缸体 — 宝马集团技术新闻稿',
        kind: 'manual',
        url: 'https://www.press.bmwgroup.com/global/article/detail/T0298784EN/the-new-bmw-m3-and-bmw-m4',
      },
      {
        label: 'Torque-to-yield rod bolts: why they are single-use (SAE)',
        labelZh: '扭矩-屈服连杆螺栓为何一次性使用（SAE）',
        kind: 'sae',
        ref: 'SAE J158 — Tightening of fasteners beyond yield',
      },
    ],
  }
}

export const PARTS: PartDef[] = [
  {
    id: 'cylinder-block',
    name: 'Cylinder Block (Crankcase)',
    system: 'block',
    build: 'block',
    position: [0, 0, 0],
    explodeOffset: [0, 0, 0],
    function:
      'Closed-deck aluminum crankcase with six cylinders. Carries the crankshaft, pistons, coolant jackets and main oil galleries. Structural core of the engine.',
    location: 'Center of the engine assembly; every other system attaches to it.',
    inspectionNotes:
      'Check cylinder walls (wire-arc sprayed iron coating) for scoring. Verify deck flatness before head installation. Main bearing caps are line-bored: keep them in original order.',
    failurePoints: 'Bore scoring on neglected oil-change intervals; head-bolt thread damage.',
    relatedPartIds: ['crankshaft', 'cylinder-head', 'oil-pan'],
    dependencies: [],
    removalOrder: -1,
    difficulty: 1,
    simplified: 'Coolant jackets and internal galleries are not modeled.',
    sources: [
      {
        label: 'BMW S58 closed-deck crankcase with wire-arc-sprayed bores — BMW Group',
        labelZh: 'BMW S58 闭式缸体与电弧喷涂缸壁 — 宝马集团',
        kind: 'manual',
        url: 'https://www.press.bmwgroup.com/global/article/detail/T0298784EN/the-new-bmw-m3-and-bmw-m4',
      },
    ],
  },
  {
    id: 'cylinder-head',
    name: 'Cylinder Head',
    system: 'head',
    build: 'head',
    position: [0, 0.78, 0],
    explodeOffset: [0, 1.6, 0],
    function:
      'Houses combustion chambers, valves, and the 3D-printed-core cooling passages unique to the S58. Routes intake charge in and exhaust gases out.',
    location: 'On top of the cylinder block, sealed by the head gasket.',
    inspectionNotes:
      'Head bolts are torque-to-yield: replace, never reuse. Check valve seat recession and gasket surface. Follow the spiral torque sequence from the center outward.',
    failurePoints: 'Gasket sealing failure after overheating events.',
    relatedPartIds: ['valve-cover', 'camshaft-intake', 'camshaft-exhaust', 'cylinder-block'],
    dependencies: ['valve-cover', 'camshaft-intake', 'camshaft-exhaust', 'intake-manifold', 'exhaust-manifold-front', 'exhaust-manifold-rear', 'timing-chain'],
    removalOrder: 19,
    difficulty: 3,
  },
  {
    id: 'valve-cover',
    name: 'Valve Cover',
    system: 'head',
    build: 'valveCover',
    position: [0, 1.22, 0],
    explodeOffset: [0, 2.8, 0],
    function:
      'Seals the valvetrain and integrates the crankcase ventilation (PCV) labyrinth. On the S58 it is a composite cover with built-in oil separators.',
    location: 'Topmost cover of the engine, above the camshafts.',
    inspectionNotes:
      'Inspect the perimeter gasket and spark-plug tube seals. Composite covers can warp: torque small bolts in sequence, do not overtighten.',
    failurePoints: 'PCV diaphragm wear causing rough idle and oil consumption.',
    relatedPartIds: ['camshaft-intake', 'camshaft-exhaust', 'cylinder-head'],
    dependencies: [],
    removalOrder: 7,
    difficulty: 1,
  },
  {
    id: 'camshaft-intake',
    name: 'Intake Camshaft',
    system: 'head',
    build: 'camshaft',
    position: [0, 1.12, 0.24],
    explodeOffset: [0, 2.2, 0.3],
    function:
      'Actuates the intake valves through roller finger followers. Phased by the VANOS unit for variable valve timing; intake valve LIFT is varied separately by the Valvetronic system.',
    location: 'Intake side (rider side of the head, +Z in this model), under the valve cover.',
    inspectionNotes:
      'Check lobe surfaces for pitting and the bearing ledges for scoring. Cam carriers must be torqued evenly: the shaft can crack if pulled down unevenly.',
    relatedPartIds: ['camshaft-exhaust', 'vanos-unit', 'valvetronic', 'valve-cover'],
    dependencies: ['valve-cover', 'timing-chain', 'vanos-unit', 'valvetronic'],
    removalOrder: 17,
    difficulty: 3,
    simplified: 'Valves, springs and finger followers are not individually modeled.',
  },
  {
    id: 'camshaft-exhaust',
    name: 'Exhaust Camshaft',
    system: 'head',
    build: 'camshaft',
    position: [0, 1.12, -0.24],
    explodeOffset: [0, 2.2, -0.3],
    function:
      'Actuates the exhaust valves and drives the two high-pressure fuel pumps via triple-lobe drive cams, arranged so the pump pair delivers every 60° of rotation.',
    location: 'Exhaust side of the head (-Z in this model), under the valve cover.',
    inspectionNotes:
      'Inspect the triple-lobe HPFP drive cams: they carry high contact load. Verify timing marks against the locking-tool position before removal.',
    relatedPartIds: ['camshaft-intake', 'hp-fuel-pump', 'hp-fuel-pump-2', 'vanos-unit'],
    dependencies: ['valve-cover', 'timing-chain', 'vanos-unit', 'hp-fuel-pump', 'hp-fuel-pump-2'],
    removalOrder: 18,
    difficulty: 3,
  },
  {
    id: 'crankshaft',
    name: 'Crankshaft',
    system: 'rotating',
    build: 'crankshaft',
    position: [0, -0.32, 0],
    explodeOffset: [0, -0.9, 0],
    function:
      'Forged steel crankshaft converting piston motion into rotation. Seven main bearings; drives the timing chain and oil pump.',
    location: 'Bottom of the block, in the crankcase main bearing saddles.',
    inspectionNotes:
      'Measure main and rod journal diameters and check bearing shells for copper exposure. Verify thrust clearance. Main cap bolts are single-use.',
    failurePoints: 'Rod bearing wear is the classic S5x failure mode under track use.',
    relatedPartIds: ['piston-1', 'harmonic-damper', 'oil-pump', 'timing-chain'],
    dependencies: ['oil-pan', 'oil-pump', 'piston-1', 'piston-2', 'piston-3', 'piston-4', 'piston-5', 'piston-6'],
    removalOrder: 33,
    difficulty: 3,
  },
  ...cylX.map((_, i) => piston(i)),
  {
    id: 'harmonic-damper',
    name: 'Harmonic Damper (Crank Pulley)',
    system: 'rotating',
    build: 'damper',
    position: [-1.95, -0.32, 0],
    explodeOffset: [-1.9, 0, 0],
    function:
      'Damps crankshaft torsional vibration and drives the accessory belt. Bolted to the crank nose.',
    location: 'Front end of the crankshaft, outside the timing cover.',
    inspectionNotes:
      'Check the elastomer ring for cracks or rotation marks. The center bolt is very high torque: counter-hold the crank, never rely on the starter.',
    relatedPartIds: ['crankshaft', 'timing-cover'],
    dependencies: [],
    removalOrder: 12,
    difficulty: 2,
  },
  {
    id: 'timing-cover',
    name: 'Timing Cover',
    system: 'timing',
    build: 'timingCover',
    position: [-1.74, 0.42, 0],
    explodeOffset: [-1.4, 0, 0],
    function: 'Seals the timing drive at the front of the engine and carries the front crank seal.',
    location: 'Front face of the engine, behind the harmonic damper.',
    inspectionNotes:
      'Sealed with liquid gasket: clean both surfaces fully and re-seal within the open time. Renew the front crank seal whenever the cover is off.',
    relatedPartIds: ['timing-chain', 'harmonic-damper'],
    dependencies: ['harmonic-damper'],
    removalOrder: 13,
    difficulty: 2,
  },
  {
    id: 'vanos-unit',
    name: 'VANOS Units (Cam Phasers)',
    system: 'timing',
    build: 'vanos',
    position: [-1.5, 1.12, 0],
    explodeOffset: [-0.9, 1.3, 0],
    function:
      'Hydraulic cam phasers on both camshafts that advance or retard valve timing for torque, response, and emissions.',
    location: 'Front ends of both camshafts, driven by the timing chain.',
    inspectionNotes:
      'Lock the camshafts with the timing tool before loosening the central valve bolts. Central bolts are single-use. Check oil control solenoid screens.',
    failurePoints: 'Rattle at cold start indicates worn phaser lock pins.',
    relatedPartIds: ['camshaft-intake', 'camshaft-exhaust', 'timing-chain'],
    dependencies: ['valve-cover', 'timing-cover'],
    removalOrder: 14,
    difficulty: 3,
    simplified: 'Both phasers and their sprockets are modeled as one serviceable unit.',
  },
  {
    id: 'timing-chain',
    name: 'Timing Chain & Guides',
    system: 'timing',
    build: 'timingChain',
    position: [-1.58, 0.4, 0],
    explodeOffset: [-0.9, 0, 0],
    function:
      'Connects the crankshaft to the VANOS sprockets, keeping valve events synchronized with piston position. Tensioned hydraulically.',
    location: 'Front of the engine, running vertically from crank to cams inside the timing cover.',
    inspectionNotes:
      'Engine MUST be locked at TDC cylinder 1 before removal: rotating cams or crank independently bends valves. Check guide rails for grooving and the tensioner for ratchet extension.',
    failurePoints: 'Guide rail wear at high mileage; chain stretch shows as VANOS fault codes.',
    relatedPartIds: ['vanos-unit', 'crankshaft', 'timing-cover'],
    dependencies: ['timing-cover', 'vanos-unit'],
    removalOrder: 15,
    difficulty: 3,
    simplified: 'Chain, guide rails, and tensioner are modeled as one loop assembly.',
  },
  {
    id: 'turbo-front',
    name: 'Turbocharger (Cyl 1–3)',
    system: 'turbo',
    build: 'turbo',
    position: [-0.75, 0.42, -1.05],
    explodeOffset: [0, 0.2, -1.6],
    function:
      'Mono-scroll turbocharger fed by cylinders 1–3. The S58 runs two small turbos in parallel for fast spool and high total airflow.',
    location: 'Exhaust side of the engine, front position, bolted to the front exhaust manifold.',
    inspectionNotes:
      'Check shaft play (axial and radial) and wheel tip damage. Inspect oil feed and return lines: a blocked return forces oil past the seals into the exhaust.',
    failurePoints: 'Wastegate actuator rattle; oil seal leakage showing as blue smoke.',
    relatedPartIds: ['exhaust-manifold-front', 'turbo-rear', 'intake-manifold'],
    dependencies: [],
    removalOrder: 8,
    difficulty: 2,
  },
  {
    id: 'turbo-rear',
    name: 'Turbocharger (Cyl 4–6)',
    system: 'turbo',
    build: 'turbo',
    position: [0.75, 0.42, -1.05],
    explodeOffset: [0, 0.2, -1.6],
    function:
      'Mono-scroll turbocharger fed by cylinders 4–6, working in parallel with the front unit.',
    location: 'Exhaust side of the engine, rear position, bolted to the rear exhaust manifold.',
    inspectionNotes:
      'Same checks as the front unit. Rear access is tighter in the chassis: inspect heat shielding and coolant line condition while removed.',
    relatedPartIds: ['exhaust-manifold-rear', 'turbo-front', 'intake-manifold'],
    dependencies: [],
    removalOrder: 9,
    difficulty: 2,
  },
  {
    id: 'exhaust-manifold-front',
    name: 'Exhaust Manifold (Cyl 1–3)',
    system: 'exhaust',
    build: 'exhaustManifold',
    position: [-0.75, 0.55, -0.62],
    explodeOffset: [0, 0, -0.9],
    function: 'Collects exhaust from cylinders 1–3 and feeds the front turbocharger.',
    location: 'Exhaust side of the cylinder head, front three ports.',
    inspectionNotes:
      'Check flange flatness and stud condition: heat-cycled studs snap easily, soak with penetrant first. Always renew gaskets.',
    relatedPartIds: ['turbo-front', 'cylinder-head'],
    dependencies: ['turbo-front'],
    removalOrder: 10,
    difficulty: 2,
  },
  {
    id: 'exhaust-manifold-rear',
    name: 'Exhaust Manifold (Cyl 4–6)',
    system: 'exhaust',
    build: 'exhaustManifold',
    position: [0.75, 0.55, -0.62],
    explodeOffset: [0, 0, -0.9],
    function: 'Collects exhaust from cylinders 4–6 and feeds the rear turbocharger.',
    location: 'Exhaust side of the cylinder head, rear three ports.',
    inspectionNotes: 'Same procedure as the front manifold. Inspect for cracking around the collector.',
    relatedPartIds: ['turbo-rear', 'cylinder-head'],
    dependencies: ['turbo-rear'],
    removalOrder: 11,
    difficulty: 2,
  },
  {
    id: 'intake-manifold',
    name: 'Intake Manifold (w/ Charge Cooler)',
    system: 'intake',
    build: 'intakeManifold',
    position: [0, 0.62, 0.78],
    explodeOffset: [0, 0.4, 1.4],
    function:
      'Distributes compressed air to all six cylinders. The plenum integrates an indirect air-to-water charge cooler served by its own low-temperature coolant circuit (dedicated electric pump, radiators and expansion tank) — separate from the main engine cooling circuit.',
    location: 'Intake side of the cylinder head (+Z), spanning all six ports.',
    inspectionNotes:
      'Check the charge cooler core for coolant seepage and pressure-test the low-temperature circuit. Renew runner seals on installation.',
    failurePoints: 'Charge cooler internal leaks let coolant into the cylinders: check plugs for steam cleaning.',
    relatedPartIds: ['throttle-body', 'coolant-pump-electric', 'cylinder-head', 'turbo-front'],
    dependencies: ['throttle-body'],
    removalOrder: 2,
    difficulty: 2,
    simplified: 'Internal charge-cooler core is not modeled separately.',
  },
  {
    id: 'throttle-body',
    name: 'Throttle Body',
    system: 'intake',
    build: 'throttleBody',
    position: [-1.18, 0.62, 1.28],
    explodeOffset: [-0.4, 0.4, 1.9],
    function:
      'Electronically controlled valve at the plenum inlet. Because the S58 meters load primarily with Valvetronic intake-valve lift, the throttle is normally held wide open and acts mainly as a backup and for boost/overrun control.',
    location: 'Front end of the intake manifold, fed by the charge pipe.',
    inspectionNotes: 'Check butterfly shaft play and carbon buildup. Run a DME throttle adaptation after reinstalling.',
    relatedPartIds: ['intake-manifold'],
    dependencies: [],
    removalOrder: 1,
    difficulty: 1,
  },
  {
    id: 'fuel-rail',
    name: 'High-Pressure Fuel Rail',
    system: 'fuel',
    build: 'fuelRail',
    position: [0, 1.0, 0.52],
    explodeOffset: [0, 2.6, 0.7],
    function: 'Stores fuel at up to 350 bar and feeds all six direct injectors.',
    location: 'Intake side of the head, above the injectors.',
    inspectionNotes:
      'Relieve system pressure before opening any fitting. High-pressure lines are single-use: never re-torque a used line.',
    relatedPartIds: ['injector-set', 'hp-fuel-pump'],
    dependencies: ['intake-manifold'],
    removalOrder: 3,
    difficulty: 2,
  },
  {
    id: 'injector-set',
    name: 'Direct Injectors (×6)',
    system: 'fuel',
    build: 'injectors',
    position: [0, 0.82, 0.42],
    explodeOffset: [0, 2.3, 0.55],
    function: 'Solenoid direct injectors spraying fuel into each combustion chamber at high pressure.',
    location: 'Intake side of the head, one per cylinder, beneath the fuel rail.',
    inspectionNotes:
      'Use the puller tool: never lever on the injector body. Renew the PTFE combustion seal with the sizing tool, and code injector trim values to the DME.',
    failurePoints: 'Combustion seal leaks cause chuffing noise and fuel trim faults.',
    relatedPartIds: ['fuel-rail', 'cylinder-head'],
    dependencies: ['fuel-rail'],
    removalOrder: 4,
    difficulty: 3,
    simplified: 'Six injectors are modeled as one service set.',
  },
  {
    id: 'hp-fuel-pump',
    name: 'High-Pressure Fuel Pump 1',
    system: 'fuel',
    build: 'hpfp',
    position: [-0.85, 1.42, -0.18],
    explodeOffset: [-0.3, 1.7, -0.2],
    function:
      'One of TWO cam-driven piston pumps (standard on every S58) raising fuel pressure from ~5 bar to up to 350 bar. The pumps run in parallel: they alternate every 30 seconds at moderate load and both deliver at full load.',
    location: 'Top front of the cylinder head, driven by a triple-lobe cam on the exhaust camshaft.',
    inspectionNotes:
      'Set the drive cam to base circle before removal. Check the roller tappet for wear and renew the O-ring. Bleed pressure before disconnecting.',
    relatedPartIds: ['hp-fuel-pump-2', 'fuel-rail', 'camshaft-exhaust'],
    dependencies: ['fuel-rail'],
    removalOrder: 5,
    difficulty: 2,
  },
  {
    id: 'hp-fuel-pump-2',
    name: 'High-Pressure Fuel Pump 2',
    system: 'fuel',
    build: 'hpfp',
    position: [-0.15, 1.42, -0.18],
    explodeOffset: [0.3, 1.7, -0.2],
    function:
      'Second of the two parallel high-pressure pumps. The two triple-lobe drive cams are phased so the pump pair delivers a pressure pulse every 60° of camshaft rotation.',
    location: 'Top of the cylinder head behind pump 1, driven by its own triple-lobe cam on the exhaust camshaft.',
    inspectionNotes:
      'Same procedure as pump 1. After replacing either pump, verify rail pressure plausibility with both volume control valves cycling.',
    relatedPartIds: ['hp-fuel-pump', 'fuel-rail', 'camshaft-exhaust'],
    dependencies: ['fuel-rail'],
    removalOrder: 6,
    difficulty: 2,
  },
  {
    id: 'water-pump',
    name: 'Coolant Pump',
    system: 'cooling',
    build: 'waterPump',
    position: [-1.82, -0.05, 0.42],
    explodeOffset: [-1.3, 0, 0.4],
    function:
      'Circulates coolant through the block and head (main engine circuit). The charge-air cooler is NOT on this circuit — it has its own low-temperature loop with a dedicated electric pump.',
    location: 'Front of the engine, low on the intake side, belt/electrically driven.',
    inspectionNotes: 'Check the weep hole for crystallized coolant traces and the bearing for play.',
    failurePoints: 'Bearing and seal wear: weeping precedes failure.',
    relatedPartIds: ['thermostat-housing', 'coolant-pump-electric', 'cylinder-block'],
    dependencies: [],
    removalOrder: 20,
    difficulty: 2,
  },
  {
    id: 'thermostat-housing',
    name: 'Thermostat Housing',
    system: 'cooling',
    build: 'thermostat',
    position: [-1.78, 0.32, 0.55],
    explodeOffset: [-1.2, 0.3, 0.6],
    function: 'Map-controlled thermostat managing engine operating temperature by routing coolant flow.',
    location: 'Front of the engine above the coolant pump.',
    inspectionNotes: 'Plastic housing becomes brittle with heat cycles: renew rather than reseal at high mileage.',
    relatedPartIds: ['water-pump'],
    dependencies: ['water-pump'],
    removalOrder: 21,
    difficulty: 1,
  },
  {
    id: 'oil-filter-housing',
    name: 'Oil Filter Housing',
    system: 'lubrication',
    build: 'oilFilter',
    position: [-1.28, 1.05, 0.45],
    explodeOffset: [-0.4, 1.5, 0.5],
    function: 'Top-mounted canister holding the oil filter element; includes the oil pressure sensor port.',
    location: 'Top front of the engine on the intake side: serviceable without lifting the car.',
    inspectionNotes: 'Renew the cap O-ring at every service. Torque the cap to spec: cracked caps leak under pressure.',
    relatedPartIds: ['oil-pump', 'oil-pan'],
    dependencies: [],
    removalOrder: 23,
    difficulty: 1,
  },
  {
    id: 'oil-pan',
    name: 'Oil Pan (Sump)',
    system: 'lubrication',
    build: 'oilPan',
    position: [0, -0.82, 0],
    explodeOffset: [0, -1.8, 0],
    function: 'Holds the engine oil supply and shields the rotating assembly. Carries the oil level sensor.',
    location: 'Bolted to the bottom of the crankcase.',
    inspectionNotes:
      'Inspect drained oil for glitter or bearing material. Sealed with liquid gasket: follow the bolt sequence on refit.',
    relatedPartIds: ['oil-pump', 'crankshaft', 'cylinder-block'],
    dependencies: [],
    removalOrder: 24,
    difficulty: 2,
  },
  {
    id: 'oil-pump',
    name: 'Oil Pump',
    system: 'lubrication',
    build: 'oilPump',
    position: [0.45, -0.62, 0],
    explodeOffset: [0.2, -1.1, 0],
    function:
      'Chain-driven, map-controlled variable-displacement pump feeding all bearings, the VANOS system, and the piston oil-spray cooling nozzles.',
    location: 'Inside the oil pan area, bolted to the bottom of the crankcase, driven off the crank.',
    inspectionNotes: 'Check pickup screen for debris: contamination here means the bottom end has been shedding material.',
    relatedPartIds: ['oil-pan', 'oil-spray-nozzles', 'crankshaft'],
    dependencies: ['oil-pan'],
    removalOrder: 25,
    difficulty: 2,
  },
  {
    id: 'valvetronic',
    name: 'Valvetronic (Variable Valve Lift)',
    system: 'head',
    build: 'valvetronic',
    position: [0, 1.3, 0.38],
    explodeOffset: [0, 2.5, 0.5],
    function:
      'Eccentric shaft, intermediate levers and servo motor that continuously vary intake-valve LIFT. This is the primary load control of the S58 — the engine breathes through the valves instead of throttling the intake.',
    location: 'Above the intake camshaft under the valve cover; the servo motor sits at the front of the head.',
    inspectionNotes:
      'Check intermediate lever guides and the eccentric-shaft sensor. Run the Valvetronic limit-stop adaptation after any work. Do not interchange intermediate levers between positions — they are classified.',
    failurePoints: 'Worn intermediate lever bearings cause uneven idle; servo motor gear wear.',
    relatedPartIds: ['camshaft-intake', 'valve-cover', 'throttle-body'],
    dependencies: ['valve-cover'],
    removalOrder: 16,
    difficulty: 3,
    simplified: 'Eccentric shaft, levers, springs and servo motor are modeled as one assembly.',
  },
  {
    id: 'coolant-pump-electric',
    name: 'Electric Coolant Pump (Charge Air)',
    system: 'cooling',
    build: 'electricPump',
    position: [-1.72, 0.55, 0.95],
    explodeOffset: [-1.2, 0.4, 0.9],
    function:
      'Electric pump of the separate low-temperature circuit that feeds the charge-air cooler inside the intake plenum. Independent of the main engine coolant pump and radiator.',
    location: 'Front of the engine on the intake side, plumbed to the charge-cooler fittings of the intake manifold.',
    inspectionNotes:
      'Activate via diagnostics and verify flow noise. Bleed the low-temperature circuit with the service function — trapped air causes heat-soak and power loss on track.',
    failurePoints: 'Pump electronics failure shows as charge-air temperature rising under sustained load.',
    relatedPartIds: ['intake-manifold', 'water-pump'],
    dependencies: [],
    removalOrder: 22,
    difficulty: 1,
    simplified: 'The low-temperature radiators and expansion tank are off-engine and not modeled.',
  },
  {
    id: 'oil-spray-nozzles',
    name: 'Piston Oil-Spray Nozzles (×6)',
    system: 'lubrication',
    build: 'oilNozzles',
    position: [0, -0.12, 0.3],
    explodeOffset: [0, -1.3, 0.7],
    function:
      'Map-controlled jets that spray oil at the piston undersides for crown cooling. Switched by a relay valve so spray is active only when piston temperatures require it.',
    location: 'Bottom of the crankcase, one nozzle per cylinder aimed up into the piston cooling gallery.',
    inspectionNotes:
      'Verify each nozzle is tight and the bore is clear — a blocked or bent nozzle overheats one piston. Check the relay valve operation with the diagnostic test.',
    failurePoints: 'Blocked nozzle leads to single-cylinder piston damage under high load.',
    relatedPartIds: ['oil-pump', 'piston-1', 'cylinder-block'],
    dependencies: ['oil-pan'],
    removalOrder: 26,
    difficulty: 2,
    simplified: 'Six nozzles and the relay valve are modeled as one service set.',
  },
]

export const PART_MAP = new Map(PARTS.map((p) => [p.id, p]))

/** Parts in guided-teardown order (block excluded). */
export const REMOVAL_SEQUENCE = PARTS.filter((p) => p.removalOrder > 0).sort(
  (a, b) => a.removalOrder - b.removalOrder,
)
