import type { EngineZhContent } from '../types'

export const zh: EngineZhContent = {
  parts: {
    'cylinder-block': { name: '气缸体（曲轴箱）' },
    'cylinder-head': { name: '气缸盖' },
    'valve-cover': { name: '气门室盖' },
    'camshaft-intake': { name: '进气凸轮轴' },
    'camshaft-exhaust': { name: '排气凸轮轴' },
    crankshaft: { name: '曲轴' },
    'piston-1': { name: '活塞与连杆 #1' },
    'piston-2': { name: '活塞与连杆 #2' },
    'piston-3': { name: '活塞与连杆 #3' },
    'piston-4': { name: '活塞与连杆 #4' },
    'harmonic-damper': { name: '扭振减振器' },
    'timing-cover': { name: '正时罩盖' },
    'svt-phasers': { name: '双 S-VT 凸轮相位器' },
    'timing-chain': { name: '正时链与导轨' },
    'exhaust-manifold': { name: '4-2-1 排气歧管' },
    'intake-manifold': { name: '进气歧管' },
    'throttle-body': { name: '节气门体' },
    'fuel-rail': { name: '高压燃油轨' },
    'injector-set': { name: '直喷喷油器（4 个）' },
    'hp-fuel-pump': { name: '高压燃油泵' },
    'water-pump': { name: '冷却液泵' },
    'thermostat-housing': { name: '节温器壳体' },
    'oil-filter-housing': { name: '机油滤清器壳体' },
    'oil-pan': { name: '油底壳' },
    'oil-pump': { name: '机油泵' },
  },
  quiz: {
    'skyg-q1': { prompt: 'Skyactiv-G 2.0 采用何种进气方式？', options: ['自然吸气', '单个双流道涡轮', '两个单流道涡轮', '机械增压'] },
    'skyg-q2': { prompt: '单击标志性的 4-2-1 排气歧管。' },
    'skyg-q3': {
      prompt: 'Skyactiv-G 为何采用长 4-2-1 排气歧管？',
      options: ['减少缸内残余废气、抑制爆震，从而实现 13:1 高压缩比', '让涡轮更快建立增压', '增加背压以利排放', '冷却进气'],
    },
    'skyg-q4': { prompt: '本模块的压缩比是多少（美规/普通燃油）？', options: ['13.0:1', '9.3:1', '10.2:1', '8.5:1'] },
    'skyg-q5': { prompt: '单击双 S-VT 凸轮相位器。' },
    'skyg-q6': {
      prompt: 'Skyactiv-G 如何控制发动机负荷？（与 Valvetronic 宝马对比）',
      options: ['主要靠节气门，辅以双 S-VT 正时', '靠可变进气门升程（节气门常开）', '靠改变增压压力', '靠停缸'],
    },
    'skyg-q7': { prompt: '单击驱动高压燃油泵的零件。' },
    'skyg-q8': { prompt: '该发动机的直喷油轨压力约为多少？', options: ['最高约 200 bar', '最高 350 bar', '最高 2000 bar', '约 4 bar（进气道喷射）'] },
    'skyg-q9': { prompt: '单击进气歧管（注意：自然吸气，无中冷器）。' },
    'skyg-q10': { prompt: '本模块使用的点火顺序是什么？', options: ['1-3-4-2', '1-5-3-6-2-4', '1-2-3-4', '1-4-2-3'] },
  },
}
