import type { PartDef } from '../../types'

const CYL_X = [-0.75, -0.25, 0.25, 0.75]

function piston(i: number): PartDef {
  return {
    id: `piston-${i + 1}`,
    name: `Piston & Connecting Rod #${i + 1}`,
    system: 'rotating',
    build: 'piston',
    position: [CYL_X[i], 0.18, 0],
    explodeOffset: [0, 1.35, 0],
    function: 'Converts combustion pressure into crankshaft torque. Skyactiv-G uses a cavity (bowl) piston crown that acts as a mini combustion chamber for the directly injected charge, enabling the 13:1 compression ratio.',
    location: `Cylinder ${i + 1}, counted from the front timing end.`,
    inspectionNotes: 'Inspect the crown cavity, ring lands, skirt coating and wrist pin fit. ND2 pistons are ~27 g lighter; do not mix with ND1 parts.',
    failurePoints: 'Carbon build-up in the crown cavity; ring land damage from knock under poor fuel quality.',
    relatedPartIds: ['crankshaft', 'cylinder-block', 'cylinder-head'],
    dependencies: ['cylinder-head', 'oil-pan', 'oil-pump'],
    removalOrder: 20 + i,
    difficulty: 3,
    simplified: 'Piston (with crown cavity), rings, wrist pin and rod are modeled as one assembly.',
  }
}

export const PARTS: PartDef[] = [
  {
    id: 'cylinder-block',
    name: 'Cylinder Block (Crankcase)',
    system: 'block',
    build: 'block',
    position: [0, 0, 0],
    explodeOffset: [0, 0, 0],
    function: 'Open-deck aluminium crankcase carrying four cylinders, the crankshaft, coolant jackets and oil galleries.',
    location: 'Structural center of the engine.',
    inspectionNotes: 'Check bore condition, deck flatness and main bearing cap order.',
    failurePoints: 'Bore scoring after oil starvation or overheating.',
    relatedPartIds: ['crankshaft', 'cylinder-head', 'oil-pan'],
    dependencies: [],
    removalOrder: -1,
    difficulty: 1,
    simplified: 'Open-deck coolant jackets and internal galleries are not modeled.',
  },
  {
    id: 'cylinder-head',
    name: 'Cylinder Head',
    system: 'head',
    build: 'head',
    position: [0, 0.78, 0],
    explodeOffset: [0, 1.45, 0],
    function: 'DOHC 16-valve aluminium head with central direct injectors. The ND2 head flows more on both intake and exhaust to support the 7,500 rpm redline.',
    location: 'Bolted to the top of the block.',
    inspectionNotes: 'Replace head bolts. Check gasket surface and valve seats before refitting.',
    relatedPartIds: ['valve-cover', 'camshaft-intake', 'camshaft-exhaust', 'intake-manifold'],
    dependencies: ['valve-cover', 'camshaft-intake', 'camshaft-exhaust', 'intake-manifold', 'exhaust-manifold', 'timing-chain'],
    removalOrder: 15,
    difficulty: 3,
  },
  {
    id: 'valve-cover',
    name: 'Valve Cover',
    system: 'head',
    build: 'valveCover',
    position: [0, 1.22, 0],
    explodeOffset: [0, 2.35, 0],
    function: 'Cam cover with crankcase ventilation and oil separation.',
    location: 'Top of the cylinder head.',
    inspectionNotes: 'Inspect gasket, PCV diaphragm and plug-tube seals.',
    failurePoints: 'PCV faults and oil leaks at the perimeter gasket.',
    relatedPartIds: ['camshaft-intake', 'camshaft-exhaust', 'svt-phasers'],
    dependencies: [],
    removalOrder: 7,
    difficulty: 1,
  },
  {
    id: 'camshaft-intake',
    name: 'Intake Camshaft',
    system: 'head',
    build: 'camshaft',
    position: [0, 1.12, 0.24],
    explodeOffset: [0, 2.0, 0.28],
    function: 'Operates the intake valves through roller-follower rocker arms; timing is varied by Dual S-VT. Lift is fixed — load is set by the throttle, not a variable-lift system.',
    location: 'Intake side of the head.',
    inspectionNotes: 'Check lobes, journals and the S-VT timing reference marks.',
    relatedPartIds: ['camshaft-exhaust', 'svt-phasers'],
    dependencies: ['valve-cover', 'timing-chain', 'svt-phasers'],
    removalOrder: 13,
    difficulty: 3,
    simplified: 'Valves, springs and roller followers are not individually modeled.',
  },
  {
    id: 'camshaft-exhaust',
    name: 'Exhaust Camshaft',
    system: 'head',
    build: 'camshaft',
    position: [0, 1.12, -0.24],
    explodeOffset: [0, 2.0, -0.28],
    function: 'Operates the exhaust valves (Dual S-VT phased) and drives the high-pressure fuel pump.',
    location: 'Exhaust side of the head.',
    inspectionNotes: 'Inspect the HPFP drive lobe and cam journals.',
    relatedPartIds: ['camshaft-intake', 'hp-fuel-pump', 'svt-phasers'],
    dependencies: ['valve-cover', 'timing-chain', 'svt-phasers', 'hp-fuel-pump'],
    removalOrder: 14,
    difficulty: 3,
  },
  {
    id: 'crankshaft',
    name: 'Crankshaft',
    system: 'rotating',
    build: 'crankshaft',
    position: [0, -0.32, 0],
    explodeOffset: [0, -0.8, 0],
    function: 'Converts the four pistons’ force pulses into rotation. The ND2 crank is strengthened for the higher redline.',
    location: 'In the crankcase main bearing saddles (five mains).',
    inspectionNotes: 'Measure journals and thrust clearance. Keep bearing caps in order.',
    relatedPartIds: ['piston-1', 'harmonic-damper', 'oil-pump'],
    dependencies: ['oil-pan', 'oil-pump', 'piston-1', 'piston-2', 'piston-3', 'piston-4'],
    removalOrder: 24,
    difficulty: 3,
  },
  ...CYL_X.map((_, i) => piston(i)),
  {
    id: 'harmonic-damper',
    name: 'Harmonic Damper',
    system: 'rotating',
    build: 'damper',
    position: [-1.45, -0.32, 0],
    explodeOffset: [-1.5, 0, 0],
    function: 'Damps crankshaft torsional vibration and drives the accessory belt.',
    location: 'Front of the crankshaft.',
    inspectionNotes: 'Check elastomer cracking and pulley runout.',
    relatedPartIds: ['crankshaft', 'timing-cover'],
    dependencies: [],
    removalOrder: 9,
    difficulty: 2,
  },
  {
    id: 'timing-cover',
    name: 'Timing Cover',
    system: 'timing',
    build: 'timingCover',
    position: [-1.22, 0.42, 0],
    explodeOffset: [-1.15, 0, 0],
    function: 'Seals the front timing-chain drive and crank seal.',
    location: 'Front face of the engine.',
    inspectionNotes: 'Clean liquid-gasket surfaces and renew the front seal.',
    relatedPartIds: ['timing-chain', 'harmonic-damper'],
    dependencies: ['harmonic-damper'],
    removalOrder: 10,
    difficulty: 2,
  },
  {
    id: 'svt-phasers',
    name: 'Dual S-VT Cam Phasers',
    system: 'timing',
    build: 'vanos',
    position: [-1.0, 1.12, 0],
    explodeOffset: [-0.85, 1.2, 0],
    function: 'Sequential Valve Timing phasers varying intake and exhaust cam timing (Dual S-VT).',
    location: 'Front ends of both camshafts.',
    inspectionNotes: 'Lock engine timing before loosening phaser bolts. Check for rattle from wear or oil contamination.',
    failurePoints: 'Slow or rattly response from phaser wear or low oil pressure.',
    relatedPartIds: ['camshaft-intake', 'camshaft-exhaust', 'timing-chain'],
    dependencies: ['valve-cover', 'timing-cover'],
    removalOrder: 11,
    difficulty: 3,
    simplified: 'Both phasers are modeled as one service unit (vanos builder reused as a visual proxy).',
  },
  {
    id: 'timing-chain',
    name: 'Timing Chain & Guides',
    system: 'timing',
    build: 'timingChain',
    position: [-1.08, 0.4, 0],
    explodeOffset: [-0.85, 0, 0],
    function: 'Synchronizes the crankshaft and camshafts.',
    location: 'Front of the engine behind the timing cover.',
    inspectionNotes: 'Lock at TDC and inspect guides/tensioner before refit.',
    relatedPartIds: ['svt-phasers', 'crankshaft'],
    dependencies: ['timing-cover', 'svt-phasers'],
    removalOrder: 12,
    difficulty: 3,
    simplified: 'Chain, guides and tensioner are one assembly.',
  },
  {
    id: 'exhaust-manifold',
    name: '4-2-1 Exhaust Manifold',
    system: 'exhaust',
    build: 'exhaustManifold',
    position: [0, 0.55, -0.62],
    explodeOffset: [0, 0, -0.9],
    function: 'Signature Skyactiv-G long-tube 4-into-2-into-1 header. Its length reduces residual exhaust gas in the cylinders, which suppresses knock and enables the high compression ratio.',
    location: 'Exhaust side of the head.',
    inspectionNotes: 'Inspect runner cracks, flange flatness and the front O2/AFR sensor.',
    failurePoints: 'Cracks at the runner junctions from thermal cycling.',
    relatedPartIds: ['cylinder-head'],
    dependencies: [],
    removalOrder: 8,
    difficulty: 2,
  },
  {
    id: 'intake-manifold',
    name: 'Intake Manifold',
    system: 'intake',
    build: 'intakeManifold',
    position: [0, 0.62, 0.78],
    explodeOffset: [0, 0.4, 1.25],
    function: 'Plenum and runners distributing filtered ambient air to the four cylinders. Naturally aspirated — there is no turbocharger or charge-air cooler.',
    location: 'Intake side of the head.',
    inspectionNotes: 'Check runner seals and the manifold-pressure sensor port.',
    relatedPartIds: ['throttle-body', 'cylinder-head'],
    dependencies: ['throttle-body'],
    removalOrder: 2,
    difficulty: 2,
  },
  {
    id: 'throttle-body',
    name: 'Throttle Body',
    system: 'intake',
    build: 'throttleBody',
    position: [-0.86, 0.62, 1.22],
    explodeOffset: [-0.35, 0.35, 1.65],
    function: 'Electronic throttle at the manifold inlet. With no variable-lift system, the throttle (with Dual S-VT) is the primary load control — unlike the Valvetronic BMW engines where it is normally wide open.',
    location: 'Front of the intake manifold.',
    inspectionNotes: 'Check deposits and perform adaptation after replacement.',
    relatedPartIds: ['intake-manifold'],
    dependencies: [],
    removalOrder: 1,
    difficulty: 1,
  },
  {
    id: 'fuel-rail',
    name: 'High-Pressure Fuel Rail',
    system: 'fuel',
    build: 'fuelRail',
    position: [0, 1.0, 0.52],
    explodeOffset: [0, 2.25, 0.65],
    function: 'Stores high-pressure fuel (up to ~200 bar) for the four direct injectors — lower than the 350-bar BMW DI rails.',
    location: 'Intake side of the head.',
    inspectionNotes: 'Depressurize before opening fittings; replace high-pressure lines.',
    relatedPartIds: ['injector-set', 'hp-fuel-pump'],
    dependencies: ['intake-manifold'],
    removalOrder: 3,
    difficulty: 2,
  },
  {
    id: 'injector-set',
    name: 'Direct Injectors (x4)',
    system: 'fuel',
    build: 'injectors',
    position: [0, 0.82, 0.42],
    explodeOffset: [0, 2.0, 0.5],
    function: 'Four multi-hole solenoid injectors spraying fuel directly into each piston-crown cavity.',
    location: 'Centrally in the head, below the rail.',
    inspectionNotes: 'Use puller tooling and renew combustion seals.',
    failurePoints: 'Combustion seal leakage and spray-pattern faults from tip deposits.',
    relatedPartIds: ['fuel-rail', 'cylinder-head'],
    dependencies: ['fuel-rail'],
    removalOrder: 4,
    difficulty: 3,
    simplified: 'Four injectors are modeled as one service set.',
  },
  {
    id: 'hp-fuel-pump',
    name: 'High-Pressure Fuel Pump',
    system: 'fuel',
    build: 'hpfp',
    position: [-0.55, 1.42, -0.18],
    explodeOffset: [-0.35, 1.55, -0.2],
    function: 'Single cam-driven pump raising fuel pressure for direct injection.',
    location: 'Top of the head, driven by the exhaust camshaft.',
    inspectionNotes: 'Set the cam to base circle before removal; inspect the tappet and O-ring.',
    relatedPartIds: ['fuel-rail', 'camshaft-exhaust'],
    dependencies: ['fuel-rail'],
    removalOrder: 5,
    difficulty: 2,
  },
  {
    id: 'water-pump',
    name: 'Coolant Pump',
    system: 'cooling',
    build: 'waterPump',
    position: [-1.28, -0.05, 0.42],
    explodeOffset: [-1.05, 0, 0.38],
    function: 'Circulates engine coolant through the block and head on a single circuit.',
    location: 'Front of the engine.',
    inspectionNotes: 'Check seepage and bearing noise.',
    relatedPartIds: ['thermostat-housing', 'cylinder-block'],
    dependencies: [],
    removalOrder: 16,
    difficulty: 2,
  },
  {
    id: 'thermostat-housing',
    name: 'Thermostat Housing',
    system: 'cooling',
    build: 'thermostat',
    position: [-1.2, 0.32, 0.55],
    explodeOffset: [-0.95, 0.3, 0.55],
    function: 'Regulates coolant flow and operating temperature.',
    location: 'Front of the engine near the coolant pump.',
    inspectionNotes: 'Inspect housing and seals.',
    relatedPartIds: ['water-pump'],
    dependencies: ['water-pump'],
    removalOrder: 17,
    difficulty: 1,
  },
  {
    id: 'oil-filter-housing',
    name: 'Oil Filter Housing',
    system: 'lubrication',
    build: 'oilFilter',
    position: [-0.82, 1.05, 0.45],
    explodeOffset: [-0.35, 1.35, 0.45],
    function: 'Holds the oil filter element and routes pressurized oil.',
    location: 'Front intake side.',
    inspectionNotes: 'Renew the cap O-ring.',
    relatedPartIds: ['oil-pump', 'oil-pan'],
    dependencies: [],
    removalOrder: 6,
    difficulty: 1,
  },
  {
    id: 'oil-pan',
    name: 'Oil Pan',
    system: 'lubrication',
    build: 'oilPan',
    position: [0, -0.82, 0],
    explodeOffset: [0, -1.55, 0],
    function: 'Stores engine oil and encloses the lower rotating assembly.',
    location: 'Bottom of the crankcase.',
    inspectionNotes: 'Inspect drained oil for debris and reseal carefully.',
    relatedPartIds: ['oil-pump', 'crankshaft'],
    dependencies: [],
    removalOrder: 18,
    difficulty: 2,
  },
  {
    id: 'oil-pump',
    name: 'Oil Pump',
    system: 'lubrication',
    build: 'oilPump',
    position: [0.25, -0.62, 0],
    explodeOffset: [0.2, -1.0, 0],
    function: 'Variable-flow oil pump that reduces pumping losses — part of the Skyactiv efficiency focus.',
    location: 'Inside the oil pan area, crank-driven.',
    inspectionNotes: 'Check the pickup screen and pump drive.',
    relatedPartIds: ['oil-pan', 'crankshaft'],
    dependencies: ['oil-pan'],
    removalOrder: 19,
    difficulty: 2,
  },
]

export const PART_MAP = new Map(PARTS.map((p) => [p.id, p]))
export const REMOVAL_SEQUENCE = PARTS.filter((p) => p.removalOrder > 0).sort((a, b) => a.removalOrder - b.removalOrder)
