import type { EngineZhContent } from '../types'

export const zh: EngineZhContent = {
  parts: {
    'cylinder-block': { name: '气缸体（铸铁曲轴箱）' },
    'cylinder-head': { name: '气缸盖（集成排气歧管）' },
    'valve-cover': { name: '气门室盖' },
    'camshaft-intake': { name: '进气凸轮轴' },
    'camshaft-exhaust': { name: '排气凸轮轴' },
    crankshaft: { name: '曲轴' },
    'piston-1': { name: '活塞与连杆 #1' },
    'piston-2': { name: '活塞与连杆 #2' },
    'piston-3': { name: '活塞与连杆 #3' },
    'piston-4': { name: '活塞与连杆 #4' },
    'harmonic-damper': { name: '扭振减振器' },
    'timing-cover': { name: '正时罩盖' },
    'cam-phasers': { name: '凸轮轴相位器（VVT）' },
    'timing-chain': { name: '正时链与导轨' },
    turbo: { name: '可变截面涡轮增压器（VGT）' },
    'intake-manifold': { name: '进气歧管（含中冷器）' },
    'throttle-body': { name: '节气门体' },
    'fuel-rail': { name: '高压燃油轨' },
    'injector-set': { name: '直喷喷油器（4 个）' },
    'port-injectors': { name: '进气道喷油器（MPI，4 个）' },
    'hp-fuel-pump': { name: '高压燃油泵' },
    'water-pump': { name: '冷却液泵' },
    'electric-coolant-pump': { name: '电子冷却液泵' },
    'thermostat-housing': { name: '热管理模块' },
    'oil-filter-housing': { name: '机油滤清器壳体' },
    'oil-pan': { name: '油底壳' },
    'oil-pump': { name: '机油泵与平衡轴' },
  },
  quiz: {
    'ea888-q1': { prompt: '单击可变截面（VGT）涡轮增压器。' },
    'ea888-q2': {
      prompt: 'EA888 的排气歧管在哪里？',
      options: ['铸造集成在气缸盖内（无独立歧管）', '螺栓固定的 4-2-1 长管头段', '分为两个歧管，每两缸一个', '没有排气歧管'],
    },
    'ea888-q3': { prompt: '单击赋予本发动机双喷射的进气道（MPI）喷油器。' },
    'ea888-q4': {
      prompt: 'EA888 如何喷油？',
      options: ['直喷（500 bar）+ 进气道（MPI）双喷射', '仅直喷', '仅进气道喷射', '机械化油器'],
    },
    'ea888-q5': { prompt: '单击同时容纳两根平衡轴的模块。' },
    'ea888-q6': {
      prompt: '与这里其他发动机相比，EA888 evo5 的曲轴箱有何不同？',
      options: ['采用灰铸铁而非铝合金', '采用镁合金', '是无缸套的开放式缸体', '没有主轴承盖'],
    },
    'ea888-q7': { prompt: '单击驱动高压燃油泵的零件。' },
    'ea888-q8': { prompt: 'evo5 将直喷油轨压力提高到……', options: ['500 bar', '200 bar', '350 bar', '2000 bar'] },
    'ea888-q9': { prompt: '单击辅助电子冷却液泵（热管理）。' },
    'ea888-q10': { prompt: '本模块使用的点火顺序是什么？', options: ['1-3-4-2', '1-5-3-6-2-4', '1-2-3-4', '1-4-2-3'] },
  },
}
