import type { PartDef } from '../../types'

import { cylX } from './geometry'

function piston(i: number): PartDef {
  return {
    id: `piston-${i + 1}`,
    name: `Piston & Connecting Rod #${i + 1}`,
    system: 'rotating',
    build: 'piston',
    position: [cylX[i], 0.18, 0],
    explodeOffset: [0, 1.35, 0],
    function: 'Converts combustion pressure into crankshaft torque. The evo5 runs a 140 mm con-rod (shortened from 144 mm) for the more extreme Miller-cycle geometry at 12.5:1.',
    location: `Cylinder ${i + 1}, counted from the front timing end.`,
    inspectionNotes: 'Inspect ring lands, skirt coating and the rod bearings. Renew torque-to-yield rod bolts.',
    failurePoints: 'Ring land damage from pre-ignition (LSPI) under high boost and low rpm.',
    relatedPartIds: ['crankshaft', 'cylinder-block'],
    dependencies: ['cylinder-head', 'oil-pan', 'oil-pump'],
    removalOrder: 22 + i,
    difficulty: 3,
    simplified: 'Piston, rings, wrist pin and rod are modeled as one assembly.',
  }
}

export const PARTS: PartDef[] = [
  {
    id: 'cylinder-block',
    name: 'Cylinder Block (Crankcase)',
    system: 'block',
    build: 'block',
    position: [0, 0, 0],
    explodeOffset: [0, 0, 0],
    function: 'Grey cast-iron crankcase carrying four cylinders, the crankshaft and two chain-driven balance shafts. The iron block is a key contrast with the aluminium blocks of the other modules.',
    location: 'Structural center of the engine.',
    inspectionNotes: 'Check bore condition, deck flatness and main bearing cap order.',
    failurePoints: 'Bore scoring after oil starvation or overheating.',
    relatedPartIds: ['crankshaft', 'cylinder-head', 'oil-pan'],
    dependencies: [],
    removalOrder: -1,
    difficulty: 1,
    simplified: 'Coolant jackets, internal galleries and the balance shafts (modeled with the oil pump) are not shown here.',
  },
  {
    id: 'cylinder-head',
    name: 'Cylinder Head (Integrated Exhaust Manifold)',
    system: 'head',
    build: 'head',
    position: [0, 0.78, 0],
    explodeOffset: [0, 1.45, 0],
    function: 'DOHC 16-valve aluminium head. The exhaust manifold is cast into the head and liquid-cooled — there is no bolt-on manifold. The turbo flanges directly to it.',
    location: 'Bolted to the top of the block.',
    inspectionNotes: 'Replace head bolts. Check gasket surface, the integrated-manifold coolant passages and valve seats before refitting.',
    failurePoints: 'Cracks in the integrated exhaust runners after severe overheating.',
    relatedPartIds: ['valve-cover', 'camshaft-intake', 'camshaft-exhaust', 'turbo'],
    dependencies: ['valve-cover', 'camshaft-intake', 'camshaft-exhaust', 'intake-manifold', 'turbo', 'timing-chain'],
    removalOrder: 16,
    difficulty: 3,
  },
  {
    id: 'valve-cover',
    name: 'Valve Cover',
    system: 'head',
    build: 'valveCover',
    position: [0, 1.22, 0],
    explodeOffset: [0, 2.35, 0],
    function: 'Cam cover with crankcase ventilation and oil separation.',
    location: 'Top of the cylinder head.',
    inspectionNotes: 'Inspect gasket, PCV diaphragm and plug-tube seals.',
    failurePoints: 'PCV faults and oil leaks at the perimeter gasket.',
    relatedPartIds: ['camshaft-intake', 'camshaft-exhaust', 'cam-phasers'],
    dependencies: [],
    removalOrder: 8,
    difficulty: 1,
  },
  {
    id: 'camshaft-intake',
    name: 'Intake Camshaft',
    system: 'head',
    build: 'camshaft',
    position: [0, 1.12, 0.24],
    explodeOffset: [0, 2.0, 0.28],
    function: 'Operates the intake valves; timing is varied by VVT (early intake-valve closing for the Miller cycle).',
    location: 'Intake side of the head.',
    inspectionNotes: 'Check lobes, journals and the VVT timing reference marks.',
    relatedPartIds: ['camshaft-exhaust', 'cam-phasers'],
    dependencies: ['valve-cover', 'timing-chain', 'cam-phasers'],
    removalOrder: 14,
    difficulty: 3,
    simplified: 'Valves, springs and followers are not individually modeled.',
  },
  {
    id: 'camshaft-exhaust',
    name: 'Exhaust Camshaft',
    system: 'head',
    build: 'camshaft',
    position: [0, 1.12, -0.24],
    explodeOffset: [0, 2.0, -0.28],
    function: 'Operates the exhaust valves (VVT-phased; some variants add AVS two-stage lift) and drives the high-pressure fuel pump.',
    location: 'Exhaust side of the head.',
    inspectionNotes: 'Inspect the HPFP drive lobe and cam journals.',
    relatedPartIds: ['camshaft-intake', 'hp-fuel-pump', 'cam-phasers'],
    dependencies: ['valve-cover', 'timing-chain', 'cam-phasers', 'hp-fuel-pump'],
    removalOrder: 15,
    difficulty: 3,
  },
  {
    id: 'crankshaft',
    name: 'Crankshaft',
    system: 'rotating',
    build: 'crankshaft',
    position: [0, -0.32, 0],
    explodeOffset: [0, -0.8, 0],
    function: 'Converts the four pistons’ force pulses into rotation. The evo5 enlarged the crankpins from 47.8 to 50.0 mm.',
    location: 'In the crankcase main bearing saddles (five mains).',
    inspectionNotes: 'Measure journals and thrust clearance. Keep bearing caps in order.',
    relatedPartIds: ['piston-1', 'harmonic-damper', 'oil-pump'],
    dependencies: ['oil-pan', 'oil-pump', 'piston-1', 'piston-2', 'piston-3', 'piston-4'],
    removalOrder: 26,
    difficulty: 3,
  },
  ...cylX.map((_, i) => piston(i)),
  {
    id: 'harmonic-damper',
    name: 'Harmonic Damper',
    system: 'rotating',
    build: 'damper',
    position: [-1.45, -0.32, 0],
    explodeOffset: [-1.5, 0, 0],
    function: 'Damps crankshaft torsional vibration and drives the accessory belt.',
    location: 'Front of the crankshaft.',
    inspectionNotes: 'Check elastomer cracking and pulley runout.',
    relatedPartIds: ['crankshaft', 'timing-cover'],
    dependencies: [],
    removalOrder: 10,
    difficulty: 2,
  },
  {
    id: 'timing-cover',
    name: 'Timing Cover',
    system: 'timing',
    build: 'timingCover',
    position: [-1.22, 0.42, 0],
    explodeOffset: [-1.15, 0, 0],
    function: 'Seals the front timing-chain drive and crank seal.',
    location: 'Front face of the engine.',
    inspectionNotes: 'Clean liquid-gasket surfaces and renew the front seal.',
    relatedPartIds: ['timing-chain', 'harmonic-damper'],
    dependencies: ['harmonic-damper'],
    removalOrder: 11,
    difficulty: 2,
  },
  {
    id: 'cam-phasers',
    name: 'Camshaft Phasers (VVT)',
    system: 'timing',
    build: 'vanos',
    position: [-1.0, 1.12, 0],
    explodeOffset: [-0.85, 1.2, 0],
    function: 'Hydraulic variable valve timing phasers on the intake and exhaust camshafts.',
    location: 'Front ends of both camshafts.',
    inspectionNotes: 'Lock engine timing before loosening phaser bolts. Check for rattle from wear or low oil pressure.',
    failurePoints: 'Slow or rattly response from phaser wear or oil contamination.',
    relatedPartIds: ['camshaft-intake', 'camshaft-exhaust', 'timing-chain'],
    dependencies: ['valve-cover', 'timing-cover'],
    removalOrder: 12,
    difficulty: 3,
    simplified: 'Both phasers are modeled as one service unit (vanos builder reused as a visual proxy).',
  },
  {
    id: 'timing-chain',
    name: 'Timing Chain & Guides',
    system: 'timing',
    build: 'timingChain',
    position: [-1.08, 0.4, 0],
    explodeOffset: [-0.85, 0, 0],
    function: 'Synchronizes the crankshaft and camshafts; a second chain drives the balance shafts.',
    location: 'Front of the engine behind the timing cover.',
    inspectionNotes: 'Lock at TDC and inspect guides/tensioner before refit. Early EA888 tensioner wear is a known failure — confirm the updated part.',
    relatedPartIds: ['cam-phasers', 'crankshaft'],
    dependencies: ['timing-cover', 'cam-phasers'],
    removalOrder: 13,
    difficulty: 3,
    simplified: 'Cam chain, balance-shaft chain, guides and tensioner are one assembly.',
  },
  {
    id: 'turbo',
    name: 'VGT Turbocharger',
    system: 'turbo',
    build: 'turbo',
    position: [0.15, 0.42, -1.05],
    explodeOffset: [0, 0.25, -1.55],
    function: 'Single variable-geometry turbocharger (moving vanes instead of a wastegate) flanged to the head’s integrated exhaust manifold — a rare gasoline VGT, enabling high boost with fast response.',
    location: 'Exhaust side, bolted to the integrated manifold on the head.',
    inspectionNotes: 'Check vane actuator travel, shaft play, oil feed and coolant lines. Carbon can seize the variable vanes.',
    failurePoints: 'Sticking VGT vanes from carbon; oil-seal leakage; actuator faults.',
    relatedPartIds: ['cylinder-head', 'intake-manifold'],
    dependencies: [],
    removalOrder: 9,
    difficulty: 2,
  },
  {
    id: 'intake-manifold',
    name: 'Intake Manifold with Charge Cooler',
    system: 'intake',
    build: 'intakeManifold',
    position: [0, 0.62, 0.78],
    explodeOffset: [0, 0.4, 1.25],
    function: 'Distributes compressed air to four cylinders with an integrated air-to-water charge cooler close-coupled for throttle response.',
    location: 'Intake side of the head.',
    inspectionNotes: 'Check charge-cooler leakage, runner-flap operation and the port-injector bungs.',
    failurePoints: 'Coolant seepage into the intake charge; intake-flap wear.',
    relatedPartIds: ['throttle-body', 'cylinder-head', 'port-injectors', 'turbo'],
    dependencies: ['throttle-body'],
    removalOrder: 2,
    difficulty: 2,
    simplified: 'Internal cooler core is not modeled separately.',
  },
  {
    id: 'throttle-body',
    name: 'Throttle Body',
    system: 'intake',
    build: 'throttleBody',
    position: [-0.86, 0.62, 1.22],
    explodeOffset: [-0.35, 0.35, 1.65],
    function: 'Electronic throttle metering airflow into the manifold.',
    location: 'Front of the intake manifold.',
    inspectionNotes: 'Check deposits and perform adaptation after replacement.',
    relatedPartIds: ['intake-manifold'],
    dependencies: [],
    removalOrder: 1,
    difficulty: 1,
  },
  {
    id: 'fuel-rail',
    name: 'High-Pressure Fuel Rail',
    system: 'fuel',
    build: 'fuelRail',
    position: [0, 1.0, 0.52],
    explodeOffset: [0, 2.25, 0.65],
    function: 'Stores high-pressure fuel up to 500 bar (raised from 350 bar) for the four direct injectors.',
    location: 'Intake side of the head.',
    inspectionNotes: 'Depressurize before opening fittings; replace high-pressure lines.',
    relatedPartIds: ['injector-set', 'hp-fuel-pump'],
    dependencies: ['intake-manifold'],
    removalOrder: 4,
    difficulty: 2,
  },
  {
    id: 'injector-set',
    name: 'Direct Injectors (x4)',
    system: 'fuel',
    build: 'injectors',
    position: [0, 0.82, 0.42],
    explodeOffset: [0, 2.0, 0.5],
    function: 'Four 500-bar solenoid injectors spraying fuel directly into the combustion chambers.',
    location: 'Centrally in the head, below the rail.',
    inspectionNotes: 'Use puller tooling and renew the PTFE combustion seals.',
    failurePoints: 'Combustion seal leakage and spray-pattern faults from tip deposits.',
    relatedPartIds: ['fuel-rail', 'cylinder-head'],
    dependencies: ['fuel-rail'],
    removalOrder: 5,
    difficulty: 3,
    simplified: 'Four injectors are modeled as one service set.',
  },
  {
    id: 'port-injectors',
    name: 'Port Injectors (MPI, x4)',
    system: 'fuel',
    build: 'injectors',
    position: [0, 0.55, 0.66],
    explodeOffset: [0, 1.1, 1.0],
    function: 'Low-pressure multi-point injectors spraying onto the intake ports. The EA888 combines port (MPI) + direct (FSI) injection to cut intake-valve carbon and aid part-load efficiency — the only dual-injection engine in this trainer.',
    location: 'Intake runners, feeding each port.',
    inspectionNotes: 'Check the low-pressure feed and O-rings; confirm fuelling switches between MPI and DI by load.',
    failurePoints: 'Clogged MPI nozzles or perished O-rings.',
    relatedPartIds: ['intake-manifold', 'injector-set'],
    dependencies: ['intake-manifold'],
    removalOrder: 3,
    difficulty: 2,
    simplified: 'Four port injectors and their low-pressure rail are modeled as one service set.',
  },
  {
    id: 'hp-fuel-pump',
    name: 'High-Pressure Fuel Pump',
    system: 'fuel',
    build: 'hpfp',
    position: [-0.55, 1.42, -0.18],
    explodeOffset: [-0.35, 1.55, -0.2],
    function: 'Single cam-driven pump raising direct-injection pressure to 500 bar.',
    location: 'Top of the head, driven by the exhaust camshaft.',
    inspectionNotes: 'Set the cam to base circle before removal; inspect the tappet and O-ring.',
    relatedPartIds: ['fuel-rail', 'camshaft-exhaust'],
    dependencies: ['fuel-rail'],
    removalOrder: 6,
    difficulty: 2,
  },
  {
    id: 'water-pump',
    name: 'Coolant Pump',
    system: 'cooling',
    build: 'waterPump',
    position: [-1.28, -0.05, 0.42],
    explodeOffset: [-1.05, 0, 0.38],
    function: 'Mechanically driven main coolant pump circulating the block and head.',
    location: 'Front of the engine.',
    inspectionNotes: 'Check seepage and bearing noise; inspect the integrated regulator if fitted.',
    relatedPartIds: ['thermostat-housing', 'electric-coolant-pump', 'cylinder-block'],
    dependencies: [],
    removalOrder: 18,
    difficulty: 2,
  },
  {
    id: 'electric-coolant-pump',
    name: 'Electric Coolant Pump',
    system: 'cooling',
    build: 'electricPump',
    position: [-1.4, 0.18, -0.32],
    explodeOffset: [-1.1, 0.2, -0.55],
    function: 'Auxiliary electric pump for the split-cooling / thermal-management strategy: it speeds warm-up and provides after-run cooling for the turbo.',
    location: 'Front of the engine, exhaust side, plumbed into the thermal-management module.',
    inspectionNotes: 'Activate via diagnostics and verify flow; check the connector and seals.',
    failurePoints: 'Pump electronics failure shows as slow warm-up or turbo heat-soak.',
    relatedPartIds: ['water-pump', 'thermostat-housing', 'turbo'],
    dependencies: [],
    removalOrder: 17,
    difficulty: 1,
    simplified: 'The split-cooling radiators and valves are simplified to this single pump.',
  },
  {
    id: 'thermostat-housing',
    name: 'Thermal-Management Module',
    system: 'cooling',
    build: 'thermostat',
    position: [-1.2, 0.32, 0.55],
    explodeOffset: [-0.95, 0.3, 0.55],
    function: 'Regulates coolant flow and operating temperature (rotary/electronic coolant control for fast warm-up).',
    location: 'Front of the engine near the coolant pumps.',
    inspectionNotes: 'Inspect the housing, control valve and seals.',
    relatedPartIds: ['water-pump', 'electric-coolant-pump'],
    dependencies: ['water-pump'],
    removalOrder: 19,
    difficulty: 1,
  },
  {
    id: 'oil-filter-housing',
    name: 'Oil Filter Housing',
    system: 'lubrication',
    build: 'oilFilter',
    position: [-0.82, 1.05, 0.45],
    explodeOffset: [-0.35, 1.35, 0.45],
    function: 'Holds the oil filter element and routes pressurized oil.',
    location: 'Front intake side.',
    inspectionNotes: 'Renew the cap O-ring and inspect cooler seals.',
    relatedPartIds: ['oil-pump', 'oil-pan'],
    dependencies: [],
    removalOrder: 7,
    difficulty: 1,
  },
  {
    id: 'oil-pan',
    name: 'Oil Pan',
    system: 'lubrication',
    build: 'oilPan',
    position: [0, -0.82, 0],
    explodeOffset: [0, -1.55, 0],
    function: 'Stores engine oil and encloses the lower rotating assembly.',
    location: 'Bottom of the crankcase.',
    inspectionNotes: 'Inspect drained oil for debris and reseal carefully.',
    relatedPartIds: ['oil-pump', 'crankshaft'],
    dependencies: [],
    removalOrder: 20,
    difficulty: 2,
  },
  {
    id: 'oil-pump',
    name: 'Oil Pump & Balance Shafts',
    system: 'lubrication',
    build: 'oilPump',
    position: [0.25, -0.62, 0],
    explodeOffset: [0.2, -1.0, 0],
    function: 'Variable-displacement oil pump integrated with the two chain-driven counter-rotating balance shafts (Lanchester balancer) that cancel the inline-four secondary shake.',
    location: 'Inside the oil pan area, chain-driven from the crank.',
    inspectionNotes: 'Check the pickup screen, pump drive and balance-shaft timing marks.',
    relatedPartIds: ['oil-pan', 'crankshaft'],
    dependencies: ['oil-pan'],
    removalOrder: 21,
    difficulty: 2,
    simplified: 'The two balance shafts are modeled as part of this pump module.',
  },
]

export const PART_MAP = new Map(PARTS.map((p) => [p.id, p]))
export const REMOVAL_SEQUENCE = PARTS.filter((p) => p.removalOrder > 0).sort((a, b) => a.removalOrder - b.removalOrder)
