import type { PartDef } from '../../types'

const CYL_X = [-1.25, -0.75, -0.25, 0.25, 0.75, 1.25]

function piston(i: number): PartDef {
  return {
    id: `piston-${i + 1}`,
    name: `Piston & Connecting Rod #${i + 1}`,
    system: 'rotating',
    build: 'piston',
    position: [CYL_X[i], 0.18, 0],
    explodeOffset: [0, 1.5, 0],
    function: 'Converts combustion pressure into crankshaft torque. The N52 runs naturally-aspirated pistons at a 10.7:1 compression ratio.',
    location: `Cylinder ${i + 1}, counted from the front (timing end) of the engine.`,
    inspectionNotes: 'Inspect ring lands, skirt coating and the rod bearing shells. Rod bolts are torque-to-yield: always replace.',
    failurePoints: 'Ring land wear at high mileage; rod bearing wear on neglected oil changes.',
    relatedPartIds: ['crankshaft', 'cylinder-block', 'cylinder-head'],
    dependencies: ['cylinder-head', 'oil-pan', 'oil-pump'],
    removalOrder: 20 + i,
    difficulty: 3,
    simplified: 'Piston, rings, wrist pin and rod are modeled as one assembly.',
  }
}

export const PARTS: PartDef[] = [
  {
    id: 'cylinder-block',
    name: 'Cylinder Block (Magnesium-Aluminium)',
    system: 'block',
    build: 'block',
    position: [0, 0, 0],
    explodeOffset: [0, 0, 0],
    function: 'Magnesium-aluminium composite crankcase carrying six cylinders, the crankshaft and the main oil galleries. A magnesium-alloy outer shell surrounds an aluminium inner block — the first water-cooled engine to use this construction.',
    location: 'Structural center of the engine; every other system attaches to it.',
    inspectionNotes: 'Check cylinder walls for scoring and deck flatness. The magnesium shell is sensitive to galvanic corrosion: use correct coolant and fasteners.',
    failurePoints: 'Coolant-transfer-pipe O-ring leaks behind the block; corrosion of the magnesium with wrong coolant.',
    relatedPartIds: ['crankshaft', 'cylinder-head', 'oil-pan'],
    dependencies: [],
    removalOrder: -1,
    difficulty: 1,
    simplified: 'Coolant jackets, the aluminium insert and internal galleries are not modeled separately.',
  },
  {
    id: 'cylinder-head',
    name: 'Cylinder Head',
    system: 'head',
    build: 'head',
    position: [0, 0.78, 0],
    explodeOffset: [0, 1.6, 0],
    function: 'Aluminium DOHC 24-valve head. Houses the combustion chambers, valves and the intake-port (MPI) injectors. Chain-driven camshafts.',
    location: 'On top of the cylinder block, sealed by the head gasket.',
    inspectionNotes: 'Head bolts are torque-to-yield: replace, never reuse. Check valve seats and the gasket surface; follow the spiral torque sequence.',
    failurePoints: 'Gasket sealing failure after overheating events.',
    relatedPartIds: ['valve-cover', 'camshaft-intake', 'camshaft-exhaust', 'intake-manifold'],
    dependencies: ['valve-cover', 'camshaft-intake', 'camshaft-exhaust', 'intake-manifold', 'exhaust-manifold', 'timing-chain'],
    removalOrder: 15,
    difficulty: 3,
  },
  {
    id: 'valve-cover',
    name: 'Valve Cover (Magnesium)',
    system: 'head',
    build: 'valveCover',
    position: [0, 1.22, 0],
    explodeOffset: [0, 2.8, 0],
    function: 'Magnesium cam cover integrating the crankcase ventilation (PCV) labyrinth and oil separation.',
    location: 'Topmost cover of the engine, above the camshafts.',
    inspectionNotes: 'Inspect the perimeter gasket and spark-plug tube seals. Do not overtighten the magnesium cover.',
    failurePoints: 'PCV diaphragm wear causing rough idle and oil consumption; valve-cover gasket oil leaks.',
    relatedPartIds: ['camshaft-intake', 'camshaft-exhaust', 'valvetronic'],
    dependencies: [],
    removalOrder: 6,
    difficulty: 1,
  },
  {
    id: 'camshaft-intake',
    name: 'Intake Camshaft',
    system: 'head',
    build: 'camshaft',
    position: [0, 1.12, 0.24],
    explodeOffset: [0, 2.2, 0.3],
    function: 'Actuates the intake valves through roller finger followers. Phased by VANOS for timing; intake-valve LIFT is varied separately by Valvetronic.',
    location: 'Intake side of the head (+Z in this model), under the valve cover.',
    inspectionNotes: 'Check lobe surfaces and bearing ledges. Torque cam carriers evenly to avoid cracking the shaft.',
    relatedPartIds: ['camshaft-exhaust', 'vanos-unit', 'valvetronic'],
    dependencies: ['valve-cover', 'timing-chain', 'vanos-unit', 'valvetronic'],
    removalOrder: 13,
    difficulty: 3,
    simplified: 'Valves, springs and finger followers are not individually modeled.',
  },
  {
    id: 'camshaft-exhaust',
    name: 'Exhaust Camshaft',
    system: 'head',
    build: 'camshaft',
    position: [0, 1.12, -0.24],
    explodeOffset: [0, 2.2, -0.3],
    function: 'Actuates the exhaust valves; phased by VANOS. Because the N52 is port-injected, it drives no high-pressure fuel pump.',
    location: 'Exhaust side of the head (-Z in this model), under the valve cover.',
    inspectionNotes: 'Inspect lobes and journals. Verify timing marks against the locking-tool position before removal.',
    relatedPartIds: ['camshaft-intake', 'vanos-unit'],
    dependencies: ['valve-cover', 'timing-chain', 'vanos-unit'],
    removalOrder: 14,
    difficulty: 3,
  },
  {
    id: 'crankshaft',
    name: 'Crankshaft',
    system: 'rotating',
    build: 'crankshaft',
    position: [0, -0.32, 0],
    explodeOffset: [0, -0.9, 0],
    function: 'Forged steel crankshaft converting piston motion into rotation. Seven main bearings; drives the timing chain and oil pump.',
    location: 'Bottom of the block, in the crankcase main bearing saddles.',
    inspectionNotes: 'Measure main and rod journals and check bearing shells. Verify thrust clearance. Main cap bolts are single-use.',
    relatedPartIds: ['piston-1', 'harmonic-damper', 'oil-pump'],
    dependencies: ['oil-pan', 'oil-pump', 'piston-1', 'piston-2', 'piston-3', 'piston-4', 'piston-5', 'piston-6'],
    removalOrder: 26,
    difficulty: 3,
  },
  ...CYL_X.map((_, i) => piston(i)),
  {
    id: 'harmonic-damper',
    name: 'Harmonic Damper (Crank Pulley)',
    system: 'rotating',
    build: 'damper',
    position: [-1.95, -0.32, 0],
    explodeOffset: [-1.9, 0, 0],
    function: 'Damps crankshaft torsional vibration and drives the accessory belt. Bolted to the crank nose.',
    location: 'Front end of the crankshaft, outside the timing cover.',
    inspectionNotes: 'Check the elastomer ring for cracks. The center bolt is very high torque: counter-hold the crank.',
    relatedPartIds: ['crankshaft', 'timing-cover'],
    dependencies: [],
    removalOrder: 8,
    difficulty: 2,
  },
  {
    id: 'timing-cover',
    name: 'Timing Cover',
    system: 'timing',
    build: 'timingCover',
    position: [-1.74, 0.42, 0],
    explodeOffset: [-1.4, 0, 0],
    function: 'Seals the timing-chain drive at the front of the engine and carries the front crank seal.',
    location: 'Front face of the engine, behind the harmonic damper.',
    inspectionNotes: 'Sealed with liquid gasket: clean both surfaces fully. Renew the front crank seal whenever the cover is off.',
    relatedPartIds: ['timing-chain', 'harmonic-damper'],
    dependencies: ['harmonic-damper'],
    removalOrder: 9,
    difficulty: 2,
  },
  {
    id: 'vanos-unit',
    name: 'VANOS Units (Cam Phasers)',
    system: 'timing',
    build: 'vanos',
    position: [-1.5, 1.12, 0],
    explodeOffset: [-0.9, 1.3, 0],
    function: 'Hydraulic cam phasers on both camshafts (double VANOS) that advance or retard valve timing.',
    location: 'Front ends of both camshafts, driven by the timing chain.',
    inspectionNotes: 'Lock the camshafts with the timing tool before loosening the central bolts. Check the oil-control solenoid screens.',
    failurePoints: 'Rattle at cold start indicates worn phaser lock pins; solenoid screen blockage sets timing faults.',
    relatedPartIds: ['camshaft-intake', 'camshaft-exhaust', 'timing-chain'],
    dependencies: ['valve-cover', 'timing-cover'],
    removalOrder: 10,
    difficulty: 3,
    simplified: 'Both phasers and their sprockets are modeled as one serviceable unit.',
  },
  {
    id: 'timing-chain',
    name: 'Timing Chain & Guides',
    system: 'timing',
    build: 'timingChain',
    position: [-1.58, 0.4, 0],
    explodeOffset: [-0.9, 0, 0],
    function: 'Connects the crankshaft to the VANOS sprockets, keeping valve events synchronized with piston position. Hydraulically tensioned.',
    location: 'Front of the engine, running vertically from crank to cams inside the timing cover.',
    inspectionNotes: 'Lock at TDC cylinder 1 before removal: rotating cams or crank independently bends valves. Check guide rails and the tensioner.',
    failurePoints: 'Guide-rail wear at high mileage; chain stretch shows as VANOS fault codes.',
    relatedPartIds: ['vanos-unit', 'crankshaft'],
    dependencies: ['timing-cover', 'vanos-unit'],
    removalOrder: 11,
    difficulty: 3,
    simplified: 'Chain, guide rails and tensioner are modeled as one loop assembly.',
  },
  {
    id: 'valvetronic',
    name: 'Valvetronic (Variable Valve Lift)',
    system: 'head',
    build: 'valvetronic',
    position: [0, 1.3, 0.38],
    explodeOffset: [0, 2.5, 0.5],
    function: 'Eccentric shaft, intermediate levers and servo motor that continuously vary intake-valve LIFT (0.18–9.9 mm). This is the primary load control — the engine breathes through the valves instead of throttling.',
    location: 'Above the intake camshaft under the valve cover; the servo motor sits at the front of the head.',
    inspectionNotes: 'Check intermediate-lever guides and the eccentric-shaft sensor. Run the Valvetronic limit-stop adaptation after any work.',
    failurePoints: 'Worn intermediate-lever bearings cause uneven idle; servo motor gear wear.',
    relatedPartIds: ['camshaft-intake', 'valve-cover', 'throttle-body'],
    dependencies: ['valve-cover'],
    removalOrder: 12,
    difficulty: 3,
    simplified: 'Eccentric shaft, levers, springs and servo motor are modeled as one assembly.',
  },
  {
    id: 'exhaust-manifold',
    name: 'Exhaust Manifold (Header)',
    system: 'exhaust',
    build: 'exhaustManifold',
    position: [0, 0.55, -0.62],
    explodeOffset: [0, 0, -0.9],
    function: 'Tubular header collecting exhaust from all six cylinders into the exhaust system. No turbocharger — naturally aspirated.',
    location: 'Exhaust side of the cylinder head.',
    inspectionNotes: 'Check flange flatness and stud condition: heat-cycled studs snap easily, soak with penetrant first. Always renew gaskets.',
    failurePoints: 'Cracks around the collector from thermal cycling.',
    relatedPartIds: ['cylinder-head'],
    dependencies: [],
    removalOrder: 7,
    difficulty: 2,
  },
  {
    id: 'intake-manifold',
    name: 'Intake Manifold (3-Stage DISA)',
    system: 'intake',
    build: 'intakeManifold',
    position: [0, 0.62, 0.78],
    explodeOffset: [0, 0.4, 1.4],
    function: 'Distributes ambient air to all six cylinders. The high-output N52 uses a 3-stage DISA variable-length manifold whose flaps switch runner length to broaden the torque curve. Naturally aspirated — no charge cooler.',
    location: 'Intake side of the cylinder head (+Z), spanning all six ports.',
    inspectionNotes: 'Check DISA flap shafts and actuators for play (a known rattle/vacuum-leak point). Renew runner seals on installation.',
    failurePoints: 'Worn DISA flap bushings cause rattle and unmetered air; broken flaps can be ingested.',
    relatedPartIds: ['throttle-body', 'cylinder-head', 'injector-set'],
    dependencies: ['throttle-body'],
    removalOrder: 2,
    difficulty: 2,
    simplified: 'The DISA flaps and actuators are represented within the manifold mesh, not as separate parts.',
  },
  {
    id: 'throttle-body',
    name: 'Throttle Body',
    system: 'intake',
    build: 'throttleBody',
    position: [-1.18, 0.62, 1.28],
    explodeOffset: [-0.4, 0.4, 1.9],
    function: 'Electronic throttle at the manifold inlet. Because the N52 meters load with Valvetronic intake-valve lift, the throttle is normally held wide open.',
    location: 'Front end of the intake manifold.',
    inspectionNotes: 'Check butterfly shaft play and carbon buildup. Run a DME throttle adaptation after reinstalling.',
    relatedPartIds: ['intake-manifold'],
    dependencies: [],
    removalOrder: 1,
    difficulty: 1,
  },
  {
    id: 'fuel-rail',
    name: 'Fuel Rail (Low-Pressure)',
    system: 'fuel',
    build: 'fuelRail',
    position: [0, 1.0, 0.52],
    explodeOffset: [0, 2.6, 0.7],
    function: 'Low-pressure rail (~3.5–5 bar, fed by the in-tank pump) supplying the six port injectors. There is no high-pressure pump or 350-bar direct-injection rail — the N52 is port-injected.',
    location: 'Intake side of the head, above the injectors.',
    inspectionNotes: 'Relieve the low fuel pressure before opening fittings; inspect the rail and injector clips.',
    relatedPartIds: ['injector-set', 'intake-manifold'],
    dependencies: ['intake-manifold'],
    removalOrder: 3,
    difficulty: 2,
  },
  {
    id: 'injector-set',
    name: 'Port Injectors (×6)',
    system: 'fuel',
    build: 'injectors',
    position: [0, 0.82, 0.42],
    explodeOffset: [0, 2.3, 0.55],
    function: 'Six solenoid port injectors spraying fuel onto the back of the intake valves (manifold injection).',
    location: 'Intake ports of the head, one per cylinder, fed by the low-pressure rail.',
    inspectionNotes: 'Renew the injector O-rings; never reuse hardened seals. Check spray pattern and fuel-trim plausibility.',
    failurePoints: 'Leaking O-rings cause hot-start and fuel-trim faults; clogged nozzles lean a cylinder.',
    relatedPartIds: ['fuel-rail', 'cylinder-head'],
    dependencies: ['fuel-rail'],
    removalOrder: 4,
    difficulty: 2,
    simplified: 'Six port injectors are modeled as one service set.',
  },
  {
    id: 'water-pump',
    name: 'Electric Coolant Pump',
    system: 'cooling',
    build: 'electricPump',
    position: [-1.82, -0.05, 0.42],
    explodeOffset: [-1.3, 0, 0.4],
    function: 'Electrically driven main coolant pump (the N52 deleted the belt-driven mechanical pump). The DME runs it on demand for fast warm-up and reduced parasitic loss.',
    location: 'Front of the engine, low on the side, plumbed into the block and head circuit.',
    inspectionNotes: 'Activate via diagnostics and verify flow. A failing pump triggers overheating warnings; replace the pump and thermostat together.',
    failurePoints: 'Pump electronics/impeller failure is a known N52 overheating cause.',
    relatedPartIds: ['thermostat-housing', 'cylinder-block'],
    dependencies: [],
    removalOrder: 16,
    difficulty: 2,
  },
  {
    id: 'thermostat-housing',
    name: 'Thermostat Housing',
    system: 'cooling',
    build: 'thermostat',
    position: [-1.78, 0.32, 0.55],
    explodeOffset: [-1.2, 0.3, 0.6],
    function: 'Map-controlled thermostat managing engine operating temperature by routing coolant flow.',
    location: 'Front of the engine near the electric coolant pump.',
    inspectionNotes: 'The plastic housing becomes brittle with heat cycles: renew rather than reseal at high mileage.',
    relatedPartIds: ['water-pump'],
    dependencies: ['water-pump'],
    removalOrder: 17,
    difficulty: 1,
  },
  {
    id: 'oil-filter-housing',
    name: 'Oil Filter Housing',
    system: 'lubrication',
    build: 'oilFilter',
    position: [-1.28, 1.05, 0.45],
    explodeOffset: [-0.4, 1.5, 0.5],
    function: 'Top-mounted canister holding the oil filter element; includes the oil-pressure sensor port.',
    location: 'Top front of the engine on the intake side: serviceable from above.',
    inspectionNotes: 'Renew the cap O-ring at every service. Torque the cap to spec: cracked caps leak under pressure.',
    relatedPartIds: ['oil-pump', 'oil-pan'],
    dependencies: [],
    removalOrder: 5,
    difficulty: 1,
  },
  {
    id: 'oil-pan',
    name: 'Oil Pan (Sump)',
    system: 'lubrication',
    build: 'oilPan',
    position: [0, -0.82, 0],
    explodeOffset: [0, -1.8, 0],
    function: 'Holds the engine oil supply and shields the rotating assembly. Carries the oil-level sensor.',
    location: 'Bolted to the bottom of the crankcase.',
    inspectionNotes: 'Inspect drained oil for glitter or bearing material. Sealed with liquid gasket: follow the bolt sequence on refit.',
    relatedPartIds: ['oil-pump', 'crankshaft'],
    dependencies: [],
    removalOrder: 18,
    difficulty: 2,
  },
  {
    id: 'oil-pump',
    name: 'Oil Pump',
    system: 'lubrication',
    build: 'oilPump',
    position: [0.45, -0.62, 0],
    explodeOffset: [0.2, -1.1, 0],
    function: 'Chain-driven oil pump (map/volume-controlled on later builds) feeding the bearings and the VANOS system.',
    location: 'Inside the oil pan area, bolted to the bottom of the crankcase, driven off the crank.',
    inspectionNotes: 'Check the pickup screen for debris: contamination here means the bottom end has been shedding material.',
    relatedPartIds: ['oil-pan', 'crankshaft'],
    dependencies: ['oil-pan'],
    removalOrder: 19,
    difficulty: 2,
  },
]

export const PART_MAP = new Map(PARTS.map((p) => [p.id, p]))

/** Parts in guided-teardown order (block excluded). */
export const REMOVAL_SEQUENCE = PARTS.filter((p) => p.removalOrder > 0).sort(
  (a, b) => a.removalOrder - b.removalOrder,
)
