import type { EngineZhContent } from '../types'

export const zh: EngineZhContent = {
  parts: {
    'cylinder-block': { name: '气缸体（曲轴箱）' },
    'cylinder-head': { name: '气缸盖' },
    'valve-cover': { name: '气门室盖' },
    'camshaft-intake': { name: '进气凸轮轴' },
    'camshaft-exhaust': { name: '排气凸轮轴' },
    crankshaft: { name: '曲轴' },
    'piston-1': { name: '活塞与连杆 #1' },
    'piston-2': { name: '活塞与连杆 #2' },
    'piston-3': { name: '活塞与连杆 #3' },
    'piston-4': { name: '活塞与连杆 #4' },
    'harmonic-damper': { name: '扭振减振器' },
    'timing-cover': { name: '正时罩盖' },
    'vanos-unit': { name: 'VANOS 单元' },
    'timing-chain': { name: '正时链与导轨' },
    turbo: { name: '双流道涡轮增压器' },
    'exhaust-manifold': { name: '双流道排气歧管' },
    'intake-manifold': { name: '进气歧管（含中冷器）' },
    'throttle-body': { name: '节气门体' },
    'fuel-rail': { name: '高压燃油轨' },
    'injector-set': { name: '直喷喷油器（4 个）' },
    'hp-fuel-pump': { name: '高压燃油泵' },
    'water-pump': { name: '冷却液泵' },
    'thermostat-housing': { name: '节温器壳体' },
    'oil-filter-housing': { name: '机油滤清器壳体' },
    'oil-pan': { name: '油底壳' },
    'oil-pump': { name: '机油泵' },
    valvetronic: { name: 'Valvetronic 可变气门升程' },
    'oil-spray-nozzles': { name: '活塞机油喷嘴（4 个）' },
  },
  quiz: {
    'b48-q1': { prompt: '单击单个双流道涡轮增压器。' },
    'b48-q2': { prompt: '本模块使用的 B48 点火顺序是什么？', options: ['1-3-4-2', '1-5-3-6-2-4', '1-2-4-3', '1-4-2-3'] },
    'b48-q3': { prompt: '单击驱动高压燃油泵的零件。' },
    'b48-q4': { prompt: '与 S58 相比，B48 的涡轮布局是……', options: ['一个双流道涡轮', '两个单流道涡轮', '自然吸气', '仅电动增压器'] },
    'b48-q5': { prompt: '单击调节进气门升程的总成。' },
    'b48-q6': { prompt: '拆下正时链之前，发动机应……', options: ['用正时工具锁定在上止点', '怠速运行五分钟', '反复反向转动', '加满冷却液'] },
    'b48-q7': { prompt: '单击集成中冷器的进气歧管。' },
    'b48-q8': { prompt: 'B48 模块建模了几个高压燃油泵？', options: ['一个', '两个', '四个', '没有'] },
    'b48-q9': { prompt: '单击包含机油集滤网的部件。' },
    'b48-q10': { prompt: 'B48 模块校准为哪种发动机布局？', options: ['2.0L 直列四缸', '3.0L 直列六缸', '4.4L V8', '1.5L 直列三缸'] },
  },
}
