import type { PartDef } from '../../types'

import { cylX } from './geometry'

function piston(i: number): PartDef {
  return {
    id: `piston-${i + 1}`,
    name: `Piston & Connecting Rod #${i + 1}`,
    system: 'rotating',
    build: 'piston',
    position: [cylX[i], 0.18, 0],
    explodeOffset: [0, 1.35, 0],
    function: 'Converts combustion pressure into crankshaft torque. B48 pistons are lightweight turbocharged direct-injection parts.',
    location: `Cylinder ${i + 1}, counted from the front timing end.`,
    inspectionNotes: 'Inspect ring lands, skirt coating, wrist pin fit, and rod bearings. Replace torque-to-yield rod bolts.',
    failurePoints: 'Ring land damage from knock; rod bearing wear under poor oil maintenance.',
    relatedPartIds: ['crankshaft', 'cylinder-block', 'oil-spray-nozzles'],
    dependencies: ['cylinder-head', 'oil-pan', 'oil-pump'],
    removalOrder: 23 + i,
    difficulty: 3,
    simplified: 'Piston, rings, wrist pin and rod are modeled as one assembly.',
  }
}

export const PARTS: PartDef[] = [
  {
    id: 'cylinder-block',
    name: 'Cylinder Block (Crankcase)',
    system: 'block',
    build: 'block',
    position: [0, 0, 0],
    explodeOffset: [0, 0, 0],
    function: 'Aluminum crankcase carrying four cylinders, crankshaft, coolant jackets and oil galleries.',
    location: 'Structural center of the engine.',
    inspectionNotes: 'Check bore condition, deck flatness and main bearing cap order.',
    failurePoints: 'Bore scoring after oil starvation or overheating.',
    relatedPartIds: ['crankshaft', 'cylinder-head', 'oil-pan'],
    dependencies: [],
    removalOrder: -1,
    difficulty: 1,
    simplified: 'Coolant jackets and internal galleries are not modeled.',
  },
  {
    id: 'cylinder-head',
    name: 'Cylinder Head',
    system: 'head',
    build: 'head',
    position: [0, 0.78, 0],
    explodeOffset: [0, 1.45, 0],
    function: 'Houses combustion chambers, valves, intake ports, exhaust ports, injectors, and Valvetronic hardware.',
    location: 'Bolted to the top of the block.',
    inspectionNotes: 'Replace head bolts. Check gasket surface and valve seats before refitting.',
    relatedPartIds: ['valve-cover', 'camshaft-intake', 'camshaft-exhaust', 'intake-manifold'],
    dependencies: ['valve-cover', 'camshaft-intake', 'camshaft-exhaust', 'intake-manifold', 'exhaust-manifold', 'timing-chain'],
    removalOrder: 17,
    difficulty: 3,
  },
  {
    id: 'valve-cover',
    name: 'Valve Cover',
    system: 'head',
    build: 'valveCover',
    position: [0, 1.22, 0],
    explodeOffset: [0, 2.35, 0],
    function: 'Composite valvetrain cover with crankcase ventilation and oil separation features.',
    location: 'Top of the cylinder head.',
    inspectionNotes: 'Inspect gasket, PCV diaphragm and plug-tube seals.',
    failurePoints: 'PCV faults and oil leaks at the perimeter gasket.',
    relatedPartIds: ['camshaft-intake', 'camshaft-exhaust', 'valvetronic'],
    dependencies: [],
    removalOrder: 7,
    difficulty: 1,
  },
  {
    id: 'camshaft-intake',
    name: 'Intake Camshaft',
    system: 'head',
    build: 'camshaft',
    position: [0, 1.12, 0.24],
    explodeOffset: [0, 2.0, 0.28],
    function: 'Operates the intake valves; timing is adjusted by VANOS while lift is varied by Valvetronic.',
    location: 'Intake side of the head.',
    inspectionNotes: 'Check lobes, bearing ledges and timing reference marks.',
    relatedPartIds: ['camshaft-exhaust', 'vanos-unit', 'valvetronic'],
    dependencies: ['valve-cover', 'timing-chain', 'vanos-unit', 'valvetronic'],
    removalOrder: 15,
    difficulty: 3,
    simplified: 'Valves, springs and followers are not individually modeled.',
  },
  {
    id: 'camshaft-exhaust',
    name: 'Exhaust Camshaft',
    system: 'head',
    build: 'camshaft',
    position: [0, 1.12, -0.24],
    explodeOffset: [0, 2.0, -0.28],
    function: 'Operates the exhaust valves and drives the high-pressure fuel pump.',
    location: 'Exhaust side of the head.',
    inspectionNotes: 'Inspect the HPFP drive lobe and cam journals.',
    relatedPartIds: ['camshaft-intake', 'hp-fuel-pump', 'vanos-unit'],
    dependencies: ['valve-cover', 'timing-chain', 'vanos-unit', 'hp-fuel-pump'],
    removalOrder: 16,
    difficulty: 3,
  },
  {
    id: 'crankshaft',
    name: 'Crankshaft',
    system: 'rotating',
    build: 'crankshaft',
    position: [0, -0.32, 0],
    explodeOffset: [0, -0.8, 0],
    function: 'Converts the four pistons’ force pulses into rotation.',
    location: 'In the crankcase main bearing saddles.',
    inspectionNotes: 'Measure journals and thrust clearance. Keep bearing caps in order.',
    relatedPartIds: ['piston-1', 'harmonic-damper', 'oil-pump'],
    dependencies: ['oil-pan', 'oil-pump', 'piston-1', 'piston-2', 'piston-3', 'piston-4'],
    removalOrder: 27,
    difficulty: 3,
  },
  ...cylX.map((_, i) => piston(i)),
  {
    id: 'harmonic-damper',
    name: 'Harmonic Damper',
    system: 'rotating',
    build: 'damper',
    position: [-1.45, -0.32, 0],
    explodeOffset: [-1.5, 0, 0],
    function: 'Damps crankshaft torsional vibration and drives the accessory belt.',
    location: 'Front of the crankshaft.',
    inspectionNotes: 'Check elastomer cracking and pulley runout.',
    relatedPartIds: ['crankshaft', 'timing-cover'],
    dependencies: [],
    removalOrder: 10,
    difficulty: 2,
  },
  {
    id: 'timing-cover',
    name: 'Timing Cover',
    system: 'timing',
    build: 'timingCover',
    position: [-1.22, 0.42, 0],
    explodeOffset: [-1.15, 0, 0],
    function: 'Seals the front timing drive and crank seal.',
    location: 'Front face of the engine.',
    inspectionNotes: 'Clean liquid-gasket surfaces and renew the front seal.',
    relatedPartIds: ['timing-chain', 'harmonic-damper'],
    dependencies: ['harmonic-damper'],
    removalOrder: 11,
    difficulty: 2,
  },
  {
    id: 'vanos-unit',
    name: 'VANOS Units',
    system: 'timing',
    build: 'vanos',
    position: [-1.0, 1.12, 0],
    explodeOffset: [-0.85, 1.2, 0],
    function: 'Hydraulic cam phasers for intake and exhaust timing.',
    location: 'Front ends of both camshafts.',
    inspectionNotes: 'Lock engine timing before loosening phaser bolts.',
    failurePoints: 'Rattle or slow response from phaser wear or oil contamination.',
    relatedPartIds: ['camshaft-intake', 'camshaft-exhaust', 'timing-chain'],
    dependencies: ['valve-cover', 'timing-cover'],
    removalOrder: 12,
    difficulty: 3,
    simplified: 'Both phasers are modeled as one service unit.',
  },
  {
    id: 'timing-chain',
    name: 'Timing Chain & Guides',
    system: 'timing',
    build: 'timingChain',
    position: [-1.08, 0.4, 0],
    explodeOffset: [-0.85, 0, 0],
    function: 'Synchronizes crankshaft and camshafts.',
    location: 'Front of the engine behind the timing cover.',
    inspectionNotes: 'Lock at TDC and inspect guides/tensioner before refit.',
    relatedPartIds: ['vanos-unit', 'crankshaft'],
    dependencies: ['timing-cover', 'vanos-unit'],
    removalOrder: 13,
    difficulty: 3,
    simplified: 'Chain, guides and tensioner are one assembly.',
  },
  {
    id: 'turbo',
    name: 'Twin-Scroll Turbocharger',
    system: 'turbo',
    build: 'turbo',
    buildParams: { scrolls: 2 },
    position: [0.15, 0.42, -1.05],
    explodeOffset: [0, 0.25, -1.55],
    function: 'Single twin-scroll turbocharger fed by separated exhaust pulse groups for fast spool.',
    location: 'Exhaust side of the engine.',
    inspectionNotes: 'Check shaft play, wastegate motion, oil feed and coolant line condition.',
    failurePoints: 'Wastegate rattle, oil seal leakage, compressor wheel damage.',
    relatedPartIds: ['exhaust-manifold', 'intake-manifold'],
    dependencies: [],
    removalOrder: 8,
    difficulty: 2,
  },
  {
    id: 'exhaust-manifold',
    name: 'Twin-Scroll Exhaust Manifold',
    system: 'exhaust',
    build: 'exhaustManifold',
    position: [0, 0.55, -0.62],
    explodeOffset: [0, 0, -0.9],
    function: 'Collects exhaust pulses and keeps twin-scroll groups separated into the turbo.',
    location: 'Exhaust side of the head.',
    inspectionNotes: 'Inspect flange flatness, studs and turbine inlet gasket.',
    relatedPartIds: ['turbo', 'cylinder-head'],
    dependencies: ['turbo'],
    removalOrder: 9,
    difficulty: 2,
  },
  {
    id: 'intake-manifold',
    name: 'Intake Manifold with Charge Cooler',
    system: 'intake',
    build: 'intakeManifold',
    position: [0, 0.62, 0.78],
    explodeOffset: [0, 0.4, 1.25],
    function: 'Distributes compressed air to four cylinders with an integrated air-to-water charge cooler.',
    location: 'Intake side of the head.',
    inspectionNotes: 'Check charge cooler leakage and renew runner seals.',
    failurePoints: 'Coolant seepage into intake charge, boost leaks at seals.',
    relatedPartIds: ['throttle-body', 'cylinder-head', 'turbo'],
    dependencies: ['throttle-body'],
    removalOrder: 2,
    difficulty: 2,
    simplified: 'Internal cooler core is not modeled separately.',
  },
  {
    id: 'throttle-body',
    name: 'Throttle Body',
    system: 'intake',
    build: 'throttleBody',
    position: [-0.86, 0.62, 1.22],
    explodeOffset: [-0.35, 0.35, 1.65],
    function: 'Electronic throttle at the manifold inlet; Valvetronic performs most load control.',
    location: 'Front of the intake manifold.',
    inspectionNotes: 'Check deposits and perform adaptation after replacement.',
    relatedPartIds: ['intake-manifold', 'valvetronic'],
    dependencies: [],
    removalOrder: 1,
    difficulty: 1,
  },
  {
    id: 'fuel-rail',
    name: 'High-Pressure Fuel Rail',
    system: 'fuel',
    build: 'fuelRail',
    position: [0, 1.0, 0.52],
    explodeOffset: [0, 2.25, 0.65],
    function: 'Stores high-pressure fuel for the four direct injectors.',
    location: 'Intake side of the head.',
    inspectionNotes: 'Depressurize before opening fittings; replace high-pressure lines.',
    relatedPartIds: ['injector-set', 'hp-fuel-pump'],
    dependencies: ['intake-manifold'],
    removalOrder: 3,
    difficulty: 2,
  },
  {
    id: 'injector-set',
    name: 'Direct Injectors (x4)',
    system: 'fuel',
    build: 'injectors',
    position: [0, 0.82, 0.42],
    explodeOffset: [0, 2.0, 0.5],
    function: 'Four solenoid direct injectors spraying fuel into the combustion chambers.',
    location: 'Intake side of the head below the rail.',
    inspectionNotes: 'Use puller tooling and renew PTFE combustion seals.',
    failurePoints: 'Combustion seal leakage and spray pattern faults.',
    relatedPartIds: ['fuel-rail', 'cylinder-head'],
    dependencies: ['fuel-rail'],
    removalOrder: 4,
    difficulty: 3,
    simplified: 'Four injectors are modeled as one service set.',
  },
  {
    id: 'hp-fuel-pump',
    name: 'High-Pressure Fuel Pump',
    system: 'fuel',
    build: 'hpfp',
    position: [-0.55, 1.42, -0.18],
    explodeOffset: [-0.35, 1.55, -0.2],
    function: 'Single cam-driven pump raising fuel pressure for direct injection.',
    location: 'Top/front of the head, driven by the exhaust camshaft.',
    inspectionNotes: 'Set cam to base circle before removal; inspect tappet and O-ring.',
    relatedPartIds: ['fuel-rail', 'camshaft-exhaust'],
    dependencies: ['fuel-rail'],
    removalOrder: 5,
    difficulty: 2,
  },
  {
    id: 'water-pump',
    name: 'Coolant Pump',
    system: 'cooling',
    build: 'waterPump',
    position: [-1.28, -0.05, 0.42],
    explodeOffset: [-1.05, 0, 0.38],
    function: 'Circulates engine coolant through the block and head.',
    location: 'Front intake side.',
    inspectionNotes: 'Check seepage and bearing noise.',
    relatedPartIds: ['thermostat-housing', 'cylinder-block'],
    dependencies: [],
    removalOrder: 18,
    difficulty: 2,
  },
  {
    id: 'thermostat-housing',
    name: 'Thermostat Housing',
    system: 'cooling',
    build: 'thermostat',
    position: [-1.2, 0.32, 0.55],
    explodeOffset: [-0.95, 0.3, 0.55],
    function: 'Regulates coolant flow and operating temperature.',
    location: 'Front of the engine near the coolant pump.',
    inspectionNotes: 'Inspect plastic housing and seals.',
    relatedPartIds: ['water-pump'],
    dependencies: ['water-pump'],
    removalOrder: 19,
    difficulty: 1,
  },
  {
    id: 'oil-filter-housing',
    name: 'Oil Filter Housing',
    system: 'lubrication',
    build: 'oilFilter',
    position: [-0.82, 1.05, 0.45],
    explodeOffset: [-0.35, 1.35, 0.45],
    function: 'Holds the oil filter element and routes pressurized oil.',
    location: 'Top/front intake side.',
    inspectionNotes: 'Renew cap O-ring and inspect cooler seals.',
    relatedPartIds: ['oil-pump', 'oil-pan'],
    dependencies: [],
    removalOrder: 6,
    difficulty: 1,
  },
  {
    id: 'oil-pan',
    name: 'Oil Pan',
    system: 'lubrication',
    build: 'oilPan',
    position: [0, -0.82, 0],
    explodeOffset: [0, -1.55, 0],
    function: 'Stores engine oil and encloses the lower rotating assembly.',
    location: 'Bottom of the crankcase.',
    inspectionNotes: 'Inspect drained oil for metallic debris and reseal carefully.',
    relatedPartIds: ['oil-pump', 'crankshaft'],
    dependencies: [],
    removalOrder: 20,
    difficulty: 2,
  },
  {
    id: 'oil-pump',
    name: 'Oil Pump',
    system: 'lubrication',
    build: 'oilPump',
    position: [0.25, -0.62, 0],
    explodeOffset: [0.2, -1.0, 0],
    function: 'Variable oil pump feeding bearings, VANOS and piston cooling jets.',
    location: 'Inside the oil pan area.',
    inspectionNotes: 'Check pickup screen and pump drive.',
    relatedPartIds: ['oil-pan', 'oil-spray-nozzles', 'crankshaft'],
    dependencies: ['oil-pan'],
    removalOrder: 21,
    difficulty: 2,
  },
  {
    id: 'valvetronic',
    name: 'Valvetronic Variable Valve Lift',
    system: 'head',
    build: 'valvetronic',
    position: [0, 1.3, 0.38],
    explodeOffset: [0, 2.2, 0.45],
    function: 'Eccentric shaft and servo system varying intake valve lift for primary load control.',
    location: 'Above the intake camshaft.',
    inspectionNotes: 'Run limit-stop adaptation after service.',
    failurePoints: 'Servo motor and eccentric-shaft sensor faults.',
    relatedPartIds: ['camshaft-intake', 'throttle-body'],
    dependencies: ['valve-cover'],
    removalOrder: 14,
    difficulty: 3,
    simplified: 'Eccentric shaft, levers and servo motor are one assembly.',
  },
  {
    id: 'oil-spray-nozzles',
    name: 'Piston Oil-Spray Nozzles (x4)',
    system: 'lubrication',
    build: 'oilNozzles',
    position: [0, -0.12, 0.3],
    explodeOffset: [0, -1.15, 0.65],
    function: 'Oil jets cooling the piston undersides.',
    location: 'Bottom of the crankcase, aimed at each piston.',
    inspectionNotes: 'Confirm nozzles are clear and correctly aimed.',
    failurePoints: 'Blocked nozzle can overheat a piston under load.',
    relatedPartIds: ['oil-pump', 'piston-1'],
    dependencies: ['oil-pan'],
    removalOrder: 22,
    difficulty: 2,
    simplified: 'Four nozzles are modeled as one service set.',
  },
]

export const PART_MAP = new Map(PARTS.map((p) => [p.id, p]))
export const REMOVAL_SEQUENCE = PARTS.filter((p) => p.removalOrder > 0).sort((a, b) => a.removalOrder - b.removalOrder)
